### ISSUE TITLE
Schema Type Error

### ISSUE THREAD

**Issue by joshbodine21** [neomerx/json-api#103]
I am using Eloquent as my ORM. So, when passing my data object into my view to be encoded, I am getting an "InvalidArgumentException - Schema is not registered for type 'Illuminate\Database\Eloquent\Collection'. File: ...Neomerx\JsonApi\Schema\Container.php. If "author" is my schema and my author data is an Eloquent collection, how do I integrate here?

**Comment by neomerx** [comment]
Describe relationship in `Schema` as

``` php
...
            'posts' => [self::DATA => $author->posts->all()],
...
```
