### ISSUE TITLE
null field sets are not recognized

### ISSUE THREAD

**Issue by mmucklo** [neomerx/json-api#107]
JsonAPI is supposed to provide for a way to return "Null" or "no" attributes for a top-level resource.

According to ethanresnick:

```
"So, for example, if your fields restrictions were: ?fields[people]=&fields[comments]=body (note the empty string value for fields[people], which means "give me no fields"), your response would look like:" ...
```

Please see this discussion for more details:
http://discuss.jsonapi.org/t/clarification-on-the-sparse-fieldset-response/221/2

So the API should handle the empty case above (_fields[people]=_), right now, unless I'm missing something, I'm not sure how to make that work with this library.

When you pass in a null fieldset, it's seems like it's ignored right now instead of being treated as null.

**Comment by neomerx** [comment]
@mmucklo fixed in `develop` branch.

Technically speaking it will be treated not as `null` (which means no field set filter) but as `[]` (no fields will be in output)
