### ISSUE TITLE
Documentation Improvements: README

### ISSUE THREAD

**Issue by fireproofsocks** [neomerx/json-api#11]
It's not clear from the examples in the README what exactly the `instance` method requires for input.  A DocBlock or a standard function description including data types would be the minimum requirement here, but it appears that the inputs are complex enough to merit more thorough descriptions.

For example, in the following snippet:

```
$encoder = Encoder::instance([
    Author::class  => AuthorSchema::class,
], new JsonEncodeOptions(JSON_PRETTY_PRINT));

echo $encoder->encode($author) . PHP_EOL;
```

What exactly is "Author::class" or "AuthorSchema::class"?  Is "::class" a class constant that was not defined in the code included in the "sample" directory?  Or are you trying to demonstrate that the input format should map a model class with a schema class?  Even after looking at the source code, I'm not entirely sure.  Also, since the `$author` instantiation isn't shown, it's unclear what exactly it is. 

A few more explanations here would go a long way and be much appreciated.  Thanks.

**Comment by boris-glumpler** [comment]
The ::class bit returns the fully qualified name of the class. Available since PHP 5.5. That means that you need to map a class to a schema. Do this for all your classes and pass it into the instance method.

**Comment by neomerx** [comment]
@fireproofsocks `::class` is a PHP language feature not this package feature. It's basically an equivalent of full class name **string** e.g `Namespace\subnamespace\YourClassName`. 

In the example I'm trying to demonstrate you should tell the coder mapping between types you encode and their schemas.

Have I answered you questions?

**Comment by neomerx** [comment]
@fireproofsocks 

Thus assuming both classes are in global namespace the sample could be written

``` php
$encoder = Encoder::instance([
    '\Author' => '\AuthorSchema',
], new JsonEncodeOptions(JSON_PRETTY_PRINT));

echo $encoder->encode($author) . PHP_EOL;
```

**Comment by neomerx** [comment]
I've updated the first sample and added comment about `::class` usage for the second one.
@fireproofsocks Do you think it should be detailed more?

**Comment by fireproofsocks** [comment]
Thank you, that's an improvement, but it should probably still be more detailed.  Suggestions follow:
1. Include the `instance` function's signature, e.g. something like

```
object  Encoder::instance ( array $array [, JsonEncodeOptions $encodeOptions )

Where the $array is an associative array mapping a class name to a class name that implements the SchemaProviderInterface.
```
- Since you can't rely on type-hinting the values in an associative array, the docs need to be clear as to what formats are required.  It's worth pointing out up-front that a schema can be a closure.
- Include common examples of the `JsonEncodeOptions`.  Pretty print is nice... are there others?

Are there any restrictions on the model class?

The description of this function is tantamount: this is the main event.  The raison d'etre of this package revolves around that function, so it probably should be given a proper introduction as such.
1. Clarify the resource type.  It was not immediately clear what the "people" type had to do with the Author class.
2. Re included objects, clarify what triggers data to show up in the primary "data" node vs. in the "included" array... I thought maybe it was the order in the array before I realized it hinged on the object passed to the `encode` function.  It's worth it here to clarify why you'd group these schemas together... would they be reused as a group and maybe pass a different object to the `encode` method?  It looks like a certain organizational structure was inferred here, but it's not explained.
3. Add a function signature for the `encode` function: it is the other critical function to this entire package as far as a dev UI is concerned.  Even if I look it up in the source code, it may not provide adequate explanations.
4. Sparse Field Sets: the dot notation here needs to be explained.  Dot notation can mean different things in different languages, and it's not native to PHP, so we're relying on some interpretation of it.  E.g. `posts.author` has a commend that "paths to be included" -- what paths?  Did you mean URLs?  Is something like "posts.author" meant to be passed in the request URLs by a user (e.g. to filter results)?
5. Per Github parlance, add a `CONTRIBUTING.md` file and put instructions for contributors there.

Re the ::class constant -- thanks!  That was not part of my PHP vocabulary.

**Comment by neomerx** [comment]
@fireproofsocks Thank you for your feedback.
I'm working on #7 which is actually quite big and requires careful reading RFC 2616. I hope I can finish it this week and get back to other issues from Monday.

**Comment by fireproofsocks** [comment]
Also: 
1. there doesn't seem to be an example for how to return collections.  
2. there should be an example for returning errors.

**Comment by neomerx** [comment]
@fireproofsocks @shabushabu I've updated the package to v0.4 and it now implements the latest RC4 JSON API which should become v1.0 right around the corner (finally no more big changes!!!).

I've also completely reworked documentation into [Wiki](https://github.com/neomerx/json-api/wiki). Please check it out.

**Comment by neomerx** [comment]
If you feel the documentation should be updated I'd be happy to receive your feedback/PRs.
