### ISSUE TITLE
Question: How can I use your package to map request to entity?

### ISSUE THREAD

**Issue by sorinstanila** [neomerx/json-api#120]
I really try to detect how you use decoders, but it is a mess in the documentation or at least it is not straight forward. You have in the examples:
{
    "data": {
        "type": "people",
        "id": "123",
        "attributes": {
            "first_name": "John",
            "last_name": "Dow"
        },
        "links": {
            "self": "http://example.com/api/v1/people/123"
        }
    }
}

How can I map this request to mappers ? I tried also the lumen implementation but I only received 400 for POST request on authors so far.

**Comment by neomerx** [comment]
First of all decoders that come with the package are not as advanced as `Encoder`. Have a look at [them](https://github.com/neomerx/json-api/tree/master/src/Decoders) it will take you less than 1 min for all three.

Advanced decoders as [this one](https://github.com/neomerx/limoncello/blob/develop/src/JsonApi/DocumentDecoder.php) are out of the package at the moment. Probably it will be moved to the package later.

It might be interesting for you how it works all together in complete solution. Here is a fully-featured [demo app](https://github.com/neomerx/limoncello-shot/tree/lumen#installation).

As I remember you're a 'Symfony guy' so Lumen solution above might be not so interesting so back to your question :smile: 

Rational behind `Encoder` + `Decoder` + `CodecMatcher`: users might send request to the same URL but with different headers `Content-Type` and `Accept`. The application should successfully find an appropriate combination of requested decoder and encoder. Then decode request and encode response.

Now you should look at [CodecMatcher wiki](https://github.com/neomerx/json-api/wiki/Parsing-API-Parameters#handling-http-accept-and-content-type-headers) one more time. Your brows might rise 'What if I have only one type for input and only one type of output all this code decoders and matchers is an equivalent to just 1 line with json_decode()?' Yes, it is :smile: But it's you to choose if you want to support various media types in your API. It's designed to be extended with your decoders (and encoders if necessary)

**Comment by neomerx** [comment]
Even deeper rational behind CodecMatcher: future versions of JSON API spec might rely on different media types (with or without media type extensions to be correct) in `Content-Type` headers. In order to deal with it `CodecMatcher` was created.

**Comment by neomerx** [comment]
If you have any further questions please don't hesitate to ask.

**Comment by Luisetelo** [comment]
Hello @neomerx,

I include your package in our laravel-based project to create new JSON API points and it is a amazing. However, I find the ausence of an advanced decoded as a drawback. I am stuying the situation of implementing a decoded based on the `documentDecoder` you mention before. I'm trying to find a example where the `documentDecoder` works but I dont find anything. Do you think this is a good start point? Please can you provide me with something?

**Comment by neomerx** [comment]
@Luisetelo I had a [similar laravel project](https://github.com/InactiveProjects/limoncello/tree/develop). It did worked however I wasn't satisfied with performance. The way laravel works with HTTP routing, containers and database models slows the app. Have a look [here](https://github.com/neomerx/rhw-l5) so you could be sure I know what I'm talking about.

Back to the 'decoder'. It's not difficult to write a decent decoder. Way more complex is support of CRUD + filtering + relationships with all tiny nuances you will be learning while struggling to make it all work together. That's what you inevitably will have to develop unless you use already developed project.

That's IMHO a [decent implementation](https://github.com/limoncello-php/json-api) of CRUD + what I mentioned for json-api and [that's a ready to use server app](https://github.com/neomerx/limoncello-flute).

If you have any further questions please don't hesitate to ask.

**Comment by lindyhopchris** [comment]
@Luisetelo 

I also use this package with Laravel. I don't have any problems with the performance in the production applications I'm using it in. Limoncello isn't an option for me because I need to use all the other functionality of Laravel.

I've got a Laravel integration package here:
https://github.com/cloudcreativity/laravel-json-api

And a demo package showing it running in a Laravel app here:
https://github.com/cloudcreativity/demo-laravel-json-api

The package parses incoming JSON API content through validators when decoding the content.

**Comment by neomerx** [comment]
@Luisetelo If you stick to laravel then the package from @lindyhopchris is definitely to recommend.

**Comment by Luisetelo** [comment]
I took a look at https://github.com/cloudcreativity/json-api however, I dont know why I didnt see the package you mention before, so unlucky. I'll revise it ASAP.

Thank you very much guys!
