### ISSUE TITLE
Please provide full class names in documentation

### ISSUE THREAD

**Issue by marhub** [neomerx/json-api#124]
instead of writing 
`$factory = new Factory();` there shoul be `$factory = new \Neomerx\JsonApi\Factories\Factory();`
that is much easier to understand.

Also there blocks like `$matcher    = $this->getCodecMatcher();` - i can't see any information about what class this method should return.

**Comment by neomerx** [comment]
While working on this I noticed that name-spacing could be enhanced for `Link` and `EncodingParameters`. As next release 0.8.0 already has a few breaking changes I decided to make these changes in 0.8.0 as well.

For more details [see](https://github.com/neomerx/json-api/wiki/Upgrade-Notes#to-080-from-071).

**Comment by neomerx** [comment]
As for code for `$matcher = $this->getCodecMatcher();` you can find how to create one on the same page but [little bit above](https://github.com/neomerx/json-api/wiki/Parsing-API-Parameters#handling-http-accept-and-content-type-headers)
