### ISSUE TITLE
Reserved words not found in JSON API spec

### ISSUE THREAD

**Issue by egeriis** [neomerx/json-api#129]
The claimed reserved words `id` and `type` (https://github.com/neomerx/json-api/blob/master/src/Document/Presenters/ElementPresenter.php#L296) are not mentioned in the JSON API spec?

**Comment by neomerx** [comment]
I bet $10 they [are mentioned](http://jsonapi.org/format/#document-resource-object-fields) :wink: 

> In other words, a resource can not have an attribute and relationship with the same name, **nor can it have an attribute or relationship named type or id.**

**Comment by egeriis** [comment]
God damnit. I thought I looked thoroughly. Thanks! :)
