### ISSUE TITLE
How to return multiple resources

### ISSUE THREAD

**Issue by dashford** [neomerx/json-api#130]
Hey,

I'm having issues returning multiple resources in the one response and am wondering how to do it properly. I'm building a search API (for a property website) and have got everything set up for returning a single advert.

However, when I retrieve multiple adverts, the response includes each advert but has one `included` array at the end with the contents of the includes of just one ad. The `included` array is missing from each of the individual results as well e.g.

```
{
    "data": [
        {...},
        {...},
        ...
        {...}
    ],
    "included": [
        {}
    ]
}
```

I'm doing something wrong but can't figure out how to return multiple instances of the same schema. To get the above result I'm looping through the data returned from my database and converting each ad to its resource, then I'm calling the `encodeData` method with this collection i.e.

``` php
// $ads is the result set from my database
$converted = [];
foreach ($ads as $ad) {
    $converted[] = new Resource\Ad\Sale($ad);
}

$response = $encoder->encodeData($converted);
```

Do I need to create another `Resource -> Schema` mapping to hold the result set overall? Any advice would be much appreciated!

**Comment by neomerx** [comment]
you can encode `array` just as you encode individual instance

``` php
$response = $encoder->encodeData($ads);
```

**Comment by neomerx** [comment]
for default includes see `getIncludePaths` in the [wiki](https://github.com/neomerx/json-api/wiki/Schemas)

**Comment by dashford** [comment]
Hey neomerx, thanks for getting back to me :smile: 

In my example I'm passing in an array of resources to the `encodeData` method, if I just pass in an array of data it won't know which schema to use. The method seems to be parsing these incorrectly or I'm doing something wrong.

For reference, I have the ad schema set up with all the default includes and relationships working. When I just want a single ad everything works perfectly. It's only when I want multiple ads in the same response that I run into issues.

**Comment by dashford** [comment]
I found a similar question in gitter: https://gitter.im/neomerx/json-api?at=56b484be073653e7151bde73

Unfortunately, I'm getting a 404 for the sample code you link to.

**Comment by dashford** [comment]
After a bit more digging I can get a similar response to what was being asked in gitter but I'm unsure why the default includes aren't being returned for each resource. When I specify a default include it only returns values for one of the resources outside of the `data` array. This is an example response I'm getting now:

```
{
    "data": [
        {
            "type": "sale",
            "id": "171271",
            "attributes": { ... },
            "relationships": { ... },
            "links": { ... }
        },
        {
            "type": "sale",
            "id": "171357",
            "attributes": { ... },
            "relationships": { ... },
            "links": { ... }
        },
        {
            "type": "sale",
            "id": "166088",
            "attributes": { ... },
            "relationships": { ... },
            "links": { ... }
        }
    ],
    "included": [
        {
            "type": "location",
            "id": "0",
            "attributes": { ... }
        }
    ]
}
```

I was expecting the include to be present in the data array for each sale object, not as a separate array. Let me know if that's an incorrect assumption! The below is an example of that:

```
{
    "data": [
        {
            "type": "sale",
            "id": "171271",
            "attributes": { ... },
            "relationships": { ... },
            "links": { ... },
            "included": [
                { ... }
            ]
        },
        {
            "type": "sale",
            "id": "171357",
            "attributes": { ... },
            "relationships": { ... },
            "links": { ... },
            "included": [
                { ... }
            ]
        },
        {
            "type": "sale",
            "id": "166088",
            "attributes": { ... },
            "relationships": { ... },
            "links": { ... },
            "included": [
                { ... }
            ]
        }
    ]
}
```

**Comment by neomerx** [comment]
@dashford either all your `Sale` object have the same `Location` or only one of them actually has something in `location` relationship.

**Comment by dashford** [comment]
Ah, thanks for that insight @neomerx :smile: The IDs of the includes are zero for the most part so they're grouping up together - when I give a unique ID to each they show up. I'll fix this in my implementation.

Many thanks for your help on this issue!
