### ISSUE TITLE
Pass custom headers via `ResponsesInterface`

### ISSUE THREAD

**Issue by lindyhopchris** [neomerx/json-api#132]
Every method in the `ResponsesInterface` needs an optional `array $headers = []` argument. The reason being that you may have custom headers that you need to include in the response.

Within the `Responses` class these should be merged with any headers it is automatically generating.

I think adding them to the interface is far more fluid than having to somehow push them onto the response at a later stage, plus makes sense with the `createResponse()` method internally within `Responses`.

**Comment by neomerx** [comment]
Yea, why not. Internally all of them use `createJsonApiResponse` which supports adding headers. Only one method `getCreatedResponse` requires adding custom header.
Can you please send PR?

**Comment by neomerx** [comment]
preferably in separate branch

**Comment by lindyhopchris** [comment]
will be able to do this tomorrow. do you want me to branch off develop?

**Comment by neomerx** [comment]
Yes branching `develop` into `feature/issue132` would be ideal

**Comment by neomerx** [comment]
I've just fixed #135 and would like to have this issue merged so I can release 0.8.1

**Comment by lindyhopchris** [comment]
@neomerx just squash merged with `develop`

**Comment by neomerx** [comment]
thanks a lot

**Comment by lindyhopchris** [comment]
no problem at all

**Comment by neomerx** [comment]
released in 0.8.1
