### ISSUE TITLE
'id' is a reserved keyword error

### ISSUE THREAD

**Issue by mtangoo** [neomerx/json-api#140]
I have this error `'id' is a reserved keyword and cannot be used as attribute name in type 'people'`
I understand that it does not like ID as attribute name. Why is that so? Does anywhere in specs say so?
I know that type cannot have name 'id' or 'type' but is that a limitation even in attributes? And what about the Post for example with ID named id?

I'm confused as to what should I do next. 
TIA.

**Comment by mtangoo** [comment]
I see unsetting it returns it anyway. What is happening?

**Comment by neomerx** [comment]
The [spec prohibits it](http://jsonapi.org/format/#document-resource-object-fields)

> In other words, a resource can not have an attribute and relationship with the same name, nor can it have an attribute or relationship named type or id.
