### ISSUE TITLE
ErrorCollection to accept ErrorInterface object

### ISSUE THREAD

**Issue by lindyhopchris** [neomerx/json-api#141]
This line:
https://github.com/neomerx/json-api/blob/master/src/Exceptions/ErrorCollection.php#L125

Should type-hint `ErrorInterface` not `Error`.

I'll submit a pull request at some point this weekend.

**Comment by lindyhopchris** [comment]
Note to self - this line as well:
https://github.com/neomerx/json-api/blob/master/src/Exceptions/JsonApiException.php#L85

**Comment by neomerx** [comment]
and this line as well

https://github.com/neomerx/json-api/blob/master/src/Exceptions/JsonApiException.php#L60

**Comment by lindyhopchris** [comment]
yep, will do the doc blocks too.

**Comment by lindyhopchris** [comment]
Another note to self:
https://github.com/neomerx/json-api/blob/master/src/Contracts/Http/ResponsesInterface.php#L97

**Comment by neomerx** [comment]
@lindyhopchris Thanks. Released as 0.8.3
