### ISSUE TITLE
Relationship has data key when none provided.

### ISSUE THREAD

**Issue by lindyhopchris** [neomerx/json-api#147]
If your schema has this for a has-many relationship:

``` php
public function getRelationships($resource, $isPrimary, array $includeRelationships)
{
    return [
        'comments' => [
            self::META => [
                'total' => $resource->totalComments,
            ],
        ],
    ];
}
```

The encoder encodes this:

``` json
relationships: {
    "comments": {
        "data": null,
        "meta": {
            "total": 5
        }
    }
}
```

The spec says:

> A “relationship object” MUST contain at least one of the following: `links` ... `data` ... `meta`.
> http://jsonapi.org/format/#document-resource-object-relationships

I.e. there is no compulsion to provide `data` if I've provided `meta`. It also says that:

> Resource linkage MUST be represented as one of the following:
> `null` for empty to-one relationships...
> http://jsonapi.org/format/#document-resource-object-linkage

I.e. `null` is not valid for the above relationship, because it is neither a to-one relationship, nor is it empty.

Failing tests pushed to branch `feature/issue147`

**Comment by neomerx** [comment]
[SHOW_DATA](https://github.com/neomerx/json-api/wiki/Schemas#showhide-data) would make your day as in [this example](https://github.com/neomerx/json-api/blob/master/tests/Encoder/EncoderTest.php#L497-L546) :wink:

**Comment by lindyhopchris** [comment]
I shouldn't have to provide `SHOW_DATA` because the spec says I don't have to include it. Surely if there is no `data` key in the relationship returned by the schema, there should be no `data` key in the output? If I want to show `data` as `null`, I can return `data` as `null`.

This feels like a bug because the encoder is not encoding what I'm returning from the schema - and the result is the output does not conform to the spec. The encoder should just be ensuring that at least one of `data`, `links` or `meta` has been returned from the schema.

**Comment by lindyhopchris** [comment]
Changing this line:
https://github.com/neomerx/json-api/blob/master/src/Schema/SchemaProvider.php#L333

to:

``` php
$isShowData    = array_key_exists(self::DATA, $desc);
```

would do it (although tests that are testing for handling of `SHOW_DATA` would need to be amended or removed).

Another reason I think this would be an improvement is because if I had decided that I didn't want to include `data`, I'm generally not going to return anything in the `DATA` key anyway - because more often than not (particularly for has-many relationships) this will result in an expensive database call.

**Comment by neomerx** [comment]
I'm thinking of slightly different variation

``` php
$isShowData = ($this->getValue($desc, self::SHOW_DATA, array_key_exists(self::DATA, $desc)) === true);
```

I've updated the line and started to update tests. So far it seems to work.

**Comment by lindyhopchris** [comment]
yeah, the advantage of that is it won't break stuff for people who are using `SHOW_DATA` at the moment, which is nice :smile:

There might however be an advantage to deprecating `SHOW_DATA` and removing it in a future release, as it's not strictly necessary as it can be detected from whether the array key exists.

**Comment by neomerx** [comment]
@lindyhopchris Have a look at `feature/issue147`

**Comment by lindyhopchris** [comment]
looks good :smile:

**Comment by neomerx** [comment]
Release or wait for other changes if any?

**Comment by lindyhopchris** [comment]
Happy for you to wait if you want - the thing I'm building that I noticed it in isn't going to be deployed to production for another few weeks.

**Comment by neomerx** [comment]
let's wait for mid of June. With your creativity I have reasons to expect something from you :smile:

**Comment by lindyhopchris** [comment]
ha! yeah, I'm currently upgrading my json-api libraries which were still on 0.6 of your library, so that's why I'm coming up with ideas at the moment!

thanks as always for the help. I've marked this as needing a doc update because when it goes into a release the wiki will need to be tweaked re: the default setting of `SHOW_DATA`. (I'm happy to do that when released.)
