### ISSUE TITLE
Allow relationship meta to be a closure.

### ISSUE THREAD

**Issue by lindyhopchris** [neomerx/json-api#148]
So the `meta` I'm returning for relationships (particularly those without `data`) quite often involve expensive database calls, especially for has-many relationships. It'd be good if the `meta` could be a `Closure` like `data` currently supports.

E.g. in Laravel this:

``` php
public function getRelationships($resource, array $includeRelationships = [])
{
    /** @var Post $resource */
    return [
        'comments' => [
            self::META => [
                'total' => $resource->comments()->count(),
            ],
        ],
    ];
}
```

Could become this:

``` php
public function getRelationships($resource, array $includeRelationships = [])
{
    /** @var Post $resource */
    return [
        'comments' => [
            self::META => function () use ($resource) {
                return [
                    'total' => $resource->comments()->count(),
                ];
            },
        ],
    ];
}
```

Should be fairly trivial to implement - I'm happy to submit a PR if you agree to it being added.

**Comment by neomerx** [comment]
`getRelationships` call -> `$resource->comments()->count()` call -> `array` creation -> encoder sets meta array for json encoding

`getRelationships` call -> `Closure` creation -> `array` creation -> encoder checks meta and executes the `Closure` -> encoder sets result for json encoding

As far as I understand meta `Closure` would be executed in 100% cases and would be executed once. So I can see overhead on closure creation (for just 1 call) and you wouldn't avoid database calls anyways. Or I just don't get the idea.

**Comment by lindyhopchris** [comment]
Hmmm... I seem to be misunderstanding something about your implementation! I'm trying to avoid the meta being created if the relationship isn't included in the result. I was assuming the object that holds the `RelationshipObject`s above would only use a `RelationshipObject` if that relationship was being included.

I.e. `RelationshipObject::getMeta()` would never be called if the relationship is not being included in the encoded resource.

If `getMeta()` is not called if the relationship is not included, then there would be a saving to returning a `Closure` for the meta.

So the chain would be:

`getRelationships` call > `Closure` creation > if relationship is included, call `getMeta` > execute `Closure`

Which means it'd stop at `Closure` creation if the relationship is not being included.

Anyway, that's what I thought was happening. I suppose I'll have to do the following instead of a `Closure`:

``` php
public function getRelationships($resource, array $includeRelationships = [])
{
    /** @var Post $resource */
    return [
        'comments' => [
            self::META => isset($includeRelationships['comment']) ? [
                'total' => $resource->comments()->count(),
            ] : null,
        ],
    ];
}
```

**Comment by neomerx** [comment]
Your solution would be faster than `Closure` even if encoder supported late calls for closures.

**Comment by lindyhopchris** [comment]
Cool, well if it's faster then that should be the approach...!

**Comment by neomerx** [comment]
@lindyhopchris btw about the speed. I'm working on a JSON API micro-framework (PSR7 and all such stuff). JSON API part is not ready yet (though I've got some good progress) but core (routing, container) is ready. It's 1,3-1,5x times faster than slim 3. Would you like to have a look?

**Comment by lindyhopchris** [comment]
@neomerx I would normally but I can't at work as it's not work-related and outside of work I'm pushing to get a personal project delivered by the end of the summer, so am mega busy. It definitely sounds interesting and would be interested to have a look at it when it's ready.

**Comment by lindyhopchris** [comment]
@neomerx back to the original topic for this...

I've realised the solution using `$includeRelationships` doesn't actually work.

The include relationships is about whether the client has requested for the related resources for that relationship to be included. However, if the relationship has no `data`, then there are no related resources to include anyway.

What I was trying to prevent is if the client has asked for sparse fieldsets, and has not included the `comments` field in those sparse fieldsets, then the database calls involved in creating the `meta` should not be called because that would be unnecessary overhead because the `comments` relationship would not be in the response.

Any idea how to solve that one?

**Comment by lindyhopchris** [comment]
(Also I was wondering what the logic was in allowing a closure to be used for the `data` field?)

**Comment by neomerx** [comment]
I got the point. You want `Encoder` to evaluate the data as late as possible when they pass sparse field set filter. It's not covered by tests now and I think it worth creation of a new branch and start experimenting with it.

**Comment by neomerx** [comment]
My current thoughts on implementation approach.

The final step of encoding is building JSON API document tree (plain `array` which then sent to `json_encode`). An interface of the component is [DocumentInterface](https://github.com/neomerx/json-api/blob/master/src/Contracts/Document/DocumentInterface.php). I think the `Closures` should be transferred all the way down to `DocumentInterface` (via filters and etc) and handled (evaluated) in `Document`.

**Comment by neomerx** [comment]
`Closure` support for `meta` looks easy to add. The only place where it's used is `Document` ([ElementPresenter](https://github.com/neomerx/json-api/blob/master/src/Document/Presenters/ElementPresenter.php#L265) to be precise which is just a part of `Document`). As for `data` part it's used in parser while parsing the input data tree so it might require more efforts.

**Comment by neomerx** [comment]
@lindyhopchris will you give it a go?

**Comment by lindyhopchris** [comment]
@neomerx happy to but can't make any commitments on when it might be - really tied up with work and personal projects at the moment. Maybe one evening next week if that's ok?

**Comment by lindyhopchris** [comment]
@neomerx have pushed to a `feature/issue148` branch. Not sure if what I've done is what you had in mind so let me know!

I wasn't sure why you've got `isDataEvaluated` in `RelationshipObject` as you know if it's not evaluated if it's a `Closure`. If there's some reason for doing this (e.g. speed) then I can do the same in `getMeta()`.

**Comment by neomerx** [comment]
I've slightly updated the branch. Can you please squash and merge it with comment `Close #148`?

**Comment by neomerx** [comment]
Your PR to wiki is welcomed :wink:

**Comment by neomerx** [comment]
@lindyhopchris ping

**Comment by lindyhopchris** [comment]
@neomerx sorry, busy with other stuff. will be able to sort this out tonight after work.

**Comment by lindyhopchris** [comment]
@neomerx have updated the docs - I was expecting it to do a pull request but it just saved the change. Sorry about that - will know for next time!

**Comment by neomerx** [comment]
@lindyhopchris Thanks a lot. That's the way wiki works. Anybody can change the wiki and I can only revert the change.

Merged. Will release in a moment.
