### ISSUE TITLE
Encoding empty array of errors.

### ISSUE THREAD

**Issue by lindyhopchris** [neomerx/json-api#151]
Encoding an empty array of errors results in:

``` json
{"data":null}
```

But I believe the following would be more appropriate?

``` json
{"errors": []}
```

I'm happy to fix this one. Expecting to get some time on this issue and the other open issue tomorrow (Weds) evening.

**Comment by neomerx** [comment]
I was so curious if this bug really existed that I couldn't resist writing a test. Sorry :smile: 

``` php
$actual  = Encoder::instance()->encodeErrors([]);

$expected = <<<EOL
{
    "errors" : []
}
EOL;

// remove formatting from 'expected'
$expected = json_encode(json_decode($expected));

$this->assertEquals($expected, $actual);
```

It was really so. Every time I close an issue (mostly enhancements) I got surprised 'How it could be in the code for so long?'

Fix was trivial so I couldn't resisted as well.

Thanks a lot for finding it.

**Comment by lindyhopchris** [comment]
Np, thanks for fixing it :smile:
