### ISSUE TITLE
Performance -  Encoding relationships

### ISSUE THREAD

**Issue by acmenna** [neomerx/json-api#153]
When relationships are encoded, it's using the full schema (attributes & relationships) despite the relationship is not included. Only type & id is needed for those cases.

Example:
Endpoint /users/1
UserSchema defines a relationship which loads an ImageSchema with all its properties & relationships but "?included=image" is not even set by default.
This performance issue is visible and severe when using lazy loading ORMs or when having external dependencies like API calls.

Let me know if you need more details. Perhaps I'm not explaining myself correctly.

Affected version: v0.5.13

Regards

**Comment by neomerx** [comment]
@acmenna Since version 0.5.X we've spent **a lot** of time to optimize the code at this department. I'm 99,9% sure the problem is already solved in current release.

If you post a small example of how you work with schema I can answer how it works in current release.

**Comment by neomerx** [comment]
[an example](https://github.com/neomerx/json-api/blob/master/tests/Encoder/EncodeSparseAndFieldSetsTest.php#L345-L385) of that we test such behaviour

**Comment by neomerx** [comment]
if you [compare Schema wiki between 0.5 and the current](https://github.com/neomerx/json-api/wiki/Schemas/_compare/8e8aea075bb23d3353c4cac78c2a67d18f5da18e...ff0b1a012e5963a2e5e8771d915c836cb469dd67) you will see that `getRelationships` has now additional parameter `array $includeList` which would contain a list of relationships to be included. With this data you can omit relationships which won't be included anyway.

**Comment by neomerx** [comment]
https://github.com/neomerx/json-api/wiki/Upgrade-Notes

**Comment by neomerx** [comment]
@acmenna I feel I have answered how to work with 'lazy' relationships and I haven't got any feedback from you for a while. If you have any further questions please don't hesitate to ask.

**Comment by acmenna** [comment]
Thanks @neomerx. We'll be upgrading to 0.8.\* this week. I will let you know if we find anything.

Thank you
