### ISSUE TITLE
Feature request: Add Schema after Encoder::instance()

### ISSUE THREAD

**Issue by Art4** [neomerx/json-api#154]
I would like to add a `Schema` after the `Encoder` was created. This way I don't have to manage a long  Data->Schema config list. Instead I can have a single `Encoder` instance and can provide a `Schema` if I need it.

``` php
$encoder = Encoder::instance([], new EncoderOptions(JSON_PRETTY_PRINT, 'http://example.com/api/v1'));

$encoder->addSchema(\Author::class, \AuthorSchema::class);

echo $encoder->encodeData($author);
```

A maybe better idea would be to add the `Schema` to the `EncodingParameters`, so the data would be encode with the specific Schema:

``` php
$encoder = Encoder::instance([], new EncoderOptions(JSON_PRETTY_PRINT, 'http://example.com/api/v1'));

$parameter = new EncodingParameters();
$parameter->setSchema(\AuthorSchema::class);

echo $encoder->encodeData($author, $parameter);
```

**Comment by neomerx** [comment]
@Art4 You can extend/inherit `ContainerInterface` (schemes container) and make `register` method public. Then make custom factory that will create `Encoder` with such empty container (and do not require any model => schema mappings). Then add custom method `Encoder::addSchema`. I think it's possible without even changing main source code.
If you are interested I will create a branch for this issue and we can try make a test case that implements it. If so have a look at [this](https://github.com/neomerx/json-api/wiki/Extending-Encoder).

**Comment by neomerx** [comment]
@Art4 Sorry for late reply. Was last 2 days on way home (stuck in Berlin btw :smile: )

**Comment by Art4** [comment]
Of course it could be possible to work around this. I wasn't sure if this is a nice feature that would be interesting also for other users. If there is interest I would be glad to open a PR for this feature.

**Comment by neomerx** [comment]
Have a look [that's probably what you wanted](https://github.com/neomerx/json-api/blob/feature/issue154/tests/Extensions/Issue154/IssueTest.php#L33-L63)

``` php
        $encoder = CustomEncoder::instance();
        $encoder->addSchema(Author::class, AuthorSchema::class);
        $author = Author::instance(9, 'Dan', 'Gebhardt');
        echo $encoder->encodeData($author);
```

**Comment by lindyhopchris** [comment]
@neomerx what's the justification for _not_ adding this method to the standard encoder interface? I'm not sure why someone shouldn't be able to add schemas to an encoder in this way?

**Comment by Art4** [comment]
@neomerx That would be the workaround, thank you very much.

My question now is the same as @lindyhopchris: Why not adding this into the standard encoder?

**Comment by neomerx** [comment]
Mostly to reduce coupling. Encoder only needs Schemes container for reading. If `addSchema` is added it will require writing as well.

Thus from one side I feel 'Yeah why not add a method for late schema register? It looks nice' but from the other 'It is more coupling and it could be easily done via extension. Do I want to have a requirement to support such method if I do custom Schemes as [this](https://github.com/limoncello-php/json-api/blob/feature/issue4/tests/Data/Schemes/CommentSchema.php) or [this](https://github.com/limoncello-php/json-api/blob/feature/issue4/src/Schema/Container.php)?'

I just feel worried if we should take additional integration risks if we are not sure this feature is widely needed and will not create additional problems.

**Comment by Art4** [comment]
> Mostly to reduce coupling. Encoder only needs Schemes container for reading. If `addSchema` is added it will require writing as well.
> 
> Thus from one side I feel 'Yeah why not add a method for late schema register? It looks nice' but from the other 'It is more coupling and it could be easily done via extension.

`Encoder`already requires `Container` for writing through `__construct()`. It was only hide inside the `Factory`. If you describe a way for writing in the `Container` interface it would be even much more cleaner.

To be honest: I don't think you can reduce coupling if you encourage the users to extend the classes. Instead you should encourage them to use composition. Thanks to the interfaces you have a very nice abstraction. So why not look at the interfaces as a "public API" for the user.

So my advices for reduce coupling are:
- use composition over inheritance
- set methods, that aren't described in an interface, to private (or protected, since users has already extended your classes)
- if possible set classes to `final` to encourage the users to use composition instead of extend

**Comment by neomerx** [comment]
I am unlikely the person who would 'encourage' other people by marking classes with `final` or moving possibly useful methods to `private`.

The ideology of the architecture is that everything is connected via interfaces (99% at least) and all internal objects are created via factory. It allows to replace **any** part of the library relatively easy with complete new implementation of interface or with reuse of existing classes.

**Comment by neomerx** [comment]
if you look at `Encoder::instance` method you will see that it is a shortcut for instantiating.

``` php
public static function instance(array $schemas = [], EncoderOptions $encodeOptions = null)
{
    $factory   = static::getFactory();
    $container = $factory->createContainer($schemas);
    $encoder   = $factory->createEncoder($container, $encodeOptions);

    return $encoder;
}
```

As you can see we could've get same result by simply sending empty Schema list and then use $container. It would take only a few lines of code but instead of desired

``` php
$encoder->addSchema(...);
```

it would be

``` php
$container->register(...);
```

So the library provides flexibility to meet various requirements and build custom solutions upon it.

**Comment by neomerx** [comment]
merged to master

**Comment by Art4** [comment]
Alright, thank you.
