### ISSUE TITLE
Add `__toString` method to `SortParameterInterface`

### ISSUE THREAD

**Issue by lindyhopchris** [neomerx/json-api#156]
It's often necessary to put the sort parameters back into URLs e.g. when generating paging links.

It would be incredibly useful if the `SortParameterInterface` had the `__toString` method on it, so that it is simple to convert the sort parameter objects back into strings when needed.

**Comment by neomerx** [comment]
Are you sure you want to add it to interface? Probably implementation?

**Comment by lindyhopchris** [comment]
Hmm... the reason for suggesting adding it to the interface is because `EncodingParametersInterface` returns an array of `SortParameterInterface` objects. So you don't know they're castable to strings unless the interface says they are. So I'd normally put it on the interface, but it is your library! So if you'd just prefer it be added to `SortParameter` then that's your call! :smile:

**Comment by neomerx** [comment]
I added the method to implementation and small changes somewhere in the code to see how string casting works (changes below). Then run test `\Neomerx\Tests\JsonApi\Http\Query\ParameterParserTest::testHeadersWithNoExtensionsButWithParameters`

```
$ git diff 
diff --git a/src/Encoder/Parameters/SortParameter.php b/src/Encoder/Parameters/SortParameter.php
index d2971a8..d92c74c 100644
--- a/src/Encoder/Parameters/SortParameter.php
+++ b/src/Encoder/Parameters/SortParameter.php
@@ -70,4 +70,9 @@ class SortParameter implements SortParameterInterface
     {
         return !$this->isAscending;
     }
+
+    public function __toString()
+    {
+        return 'Hello';
+    }
 }
diff --git a/src/Http/Query/QueryParametersParser.php b/src/Http/Query/QueryParametersParser.php
index 7a80391..319707a 100644
--- a/src/Http/Query/QueryParametersParser.php
+++ b/src/Http/Query/QueryParametersParser.php
@@ -112,7 +112,9 @@ class QueryParametersParser implements QueryParametersParserInterface, LoggerAwa
                     $isDesc = ($param[0] === '-') : E::throwException(new E([], E::HTTP_CODE_BAD_REQUEST));
                 $sortField = ltrim($param, '+-');
                 empty($sortField) === false ?: E::throwException(new E([], E::HTTP_CODE_BAD_REQUEST));
-                $sortParams[] = $this->factory->createSortParam($sortField, $isDesc === false);
+                $sortParams[] = $tmp = $this->factory->createSortParam($sortField, $isDesc === false);
+
+                $foo = (string)$tmp;
             }
         }
         return $sortParams;
```

It seems it works. So no need to actually add to interface, I think.
![image](https://cloud.githubusercontent.com/assets/10420662/17753410/6918adec-64d8-11e6-9ea4-7207669e5f79.png)

**Comment by neomerx** [comment]
I got your point that adding it to interface is like explicitly saying it can be converted to string.
Can you post the code for `class` level changes and we can add interface method if needed later?

**Comment by lindyhopchris** [comment]
Yeah, that makes sense - add it to the class and it can go in the interface if needed later. I should be able to do that at some point this weekend.

**Comment by neomerx** [comment]
ping @lindyhopchris

**Comment by lindyhopchris** [comment]
Sorry, been ill so not been working. Will look at this today

**Comment by lindyhopchris** [comment]
@neomerx have pushed to a feature branch. Can squash merge to `develop` if you're happy

**Comment by neomerx** [comment]
Looks fine. Thanks.
