### ISSUE TITLE
Slim-Integration

### ISSUE THREAD

**Issue by ratbird** [neomerx/json-api#160]
Some months ago I implemented a Slim 3 integration using neomerx/json-api v0.6.x and neomerx/limoncello v0.5.1.

After the release of neomerx/json-api v0.8.x I am left out in the cold as I have no clue how to implement this.

I saw the LaravelServiceProvider.php and LumenServiceProvider.php in the develop branch of limoncello but I could use some (conclusive) hints how to go about integrating json-api into Slim...

Could you please assist?

**Comment by neomerx** [comment]
@ratbird There were no dramatical changes in API. You can easily get up-to-date with [upgrade notes](https://github.com/neomerx/json-api/wiki/Upgrade-Notes).

Also you may see a sample application implementation [flute](https://github.com/neomerx/limoncello-flute) and [integration/API imlementation](https://github.com/limoncello-php/json-api).

**Comment by neomerx** [comment]
If you have any further questions please don't hesitate to ask.
