### ISSUE TITLE
How to use "to Many" Relationships in Schema

### ISSUE THREAD

**Issue by sebtoombs** [neomerx/json-api#163]
When attempting to encode a resource that has a relationship to a single other resource (i.e. what is often referred to as a "toOne" resource) the Parser throws the following error:

`Schema is not registered for a resource at path "toOneResource"`

Note that the error only occurs when the relationship is **not** empty. If the relationship is empty, the data is generated correctly. (e.g. below)

`data: {}`

instead of

`data: []`

Is this a bug, or are "toMany" relationships not supported?

**Comment by neomerx** [comment]
It supports both types of relationships to single resource and collections. Encoder understands that `array`, `Iterator` or `Traversable` are `toMany` relationships and acts accordingly. You just provide your data in `Schema` and encoder does the rest. That's an [example for both types of relationships](https://github.com/neomerx/json-api/blob/master/tests/Data/PostSchema.php#L70-L71) and how [encoding result looks like](https://github.com/neomerx/json-api/blob/master/tests/Encoder/EncoderTest.php#L241-L276).
Apart from numerous encoding samples there is a [wiki](https://github.com/neomerx/json-api/wiki/Schemas) as well.

**Comment by sebtoombs** [comment]
Thanks, I had already reviewed all of that information.

Turned out the issue was with types, Doctrine returning a proxy but the Schema expecting an entity.

Thanks for the reply.

**Comment by neomerx** [comment]
Long long time ago issue with doctrine proxies was solved in #40 

I'm closing the issue. If you have any further questions please don't hesitate to ask.
