### ISSUE TITLE
Nested Included in relationship

### ISSUE THREAD

**Issue by geniuscd** [neomerx/json-api#164]
I came across an issue in my schema, where i have a Main Model that have models in his properties.
Its clear how to include them in the relationships. but what if these models also have models in there structure.
I need to include the nested models in the main included.
i didn't find a topic that covers this issue.
anyone ?  is this issue #163 sort of related?
please label it as a question

**Comment by neomerx** [comment]
> I came across an issue in my schema, where i have a Main Model that have models in his properties.

better to say 'in relationships'

> but what if these models also have models in there structure.

in their 'relationships'

No probs. Just set up schemes for your models and encode top level 'main model'. The encoder will automatically walk through relationships and produce result as

data
  |_ main resource
included
 |_ main's child 1
 |_ main's child 2
...
 |_ grand children will also be here on the list

[sample from tests package](https://github.com/neomerx/json-api/blob/master/tests/Encoder/EncodeSparseAndFieldSetsTest.php#L88-L179)

**Comment by geniuscd** [comment]
Thank you for your swift reply
i have versions 0.8.8 install via composer and thats exactly what i'm doing.
should i update the package ?

**Comment by neomerx** [comment]
Make sure you instruct `Encoder` which paths should be included with `EncodingParameters` [as here](https://github.com/neomerx/json-api/blob/master/tests/Encoder/EncodeSparseAndFieldSetsTest.php#L99-L102). You don't want whole database to be included by default, do you?

**Comment by geniuscd** [comment]
I'm aware of the EncodingParameters object. I did an implementation in a web app using SLIM where the user have the ability to choose his included object and attributes, according to the JSONAPI.org v1.0, through the query string.
I think the problem still exists. I tried it. the encoder doesn't iterate in all the structure. maybe im missing something. i can't share all the code its huge, attached a sample file that contains three models nested. the URI object isn't showing in the included.

[models.txt](https://github.com/neomerx/json-api/files/613308/models.txt)

**Comment by neomerx** [comment]
I think it's 99,99% the problem not in the lib code and without seeing your code it's difficult to say anything definitive about it.
I can recommend you to look closer to [sample app](https://github.com/neomerx/json-api/tree/master/sample) and on this [complete sample with included resources](https://github.com/neomerx/json-api/blob/master/sample/Application/EncodeSamples.php#L61-L81). [Default include paths could be configured](https://github.com/neomerx/json-api/blob/master/sample/Schemas/SiteSchema.php#L65-L72).

Structure of data should be obvious for you site -> posts -> comments -> authors. A 'site' will be encoded with included resources.

Check your relationships in Schemes, check input data.

clone the project and run `composer up` in sample folder then `php sample.php`. My output
```
...
Neomerx JSON API sample application (included objects)
{
    "data": {
        "type": "sites",
        "id": "1",
        "attributes": {
            "name": "JSON API Samples"
        },
        "relationships": {
            "posts": {
                "data": [
                    {
                        "type": "posts",
                        "id": "321"
                    }
                ],
                "links": {
                    "some-sublink": "http:\/\/example.com\/sites\/1\/resource-sublink",
                    "external-link": "www.example.com"
                }
            }
        },
        "links": {
            "self": "http:\/\/example.com\/sites\/1"
        }
    },
    "included": [
        {
            "type": "people",
            "id": "123",
            "attributes": {
                "first_name": "John",
                "last_name": "Dow"
            }
        },
        {
            "type": "comments",
            "id": "456",
            "attributes": {
                "body": "Included objects work as easy as basic ones"
            },
            "relationships": {
                "author": {
                    "data": {
                        "type": "people",
                        "id": "123"
                    }
                }
            }
        },
        {
            "type": "comments",
            "id": "789",
            "attributes": {
                "body": "Let's try!"
            },
            "relationships": {
                "author": {
                    "data": {
                        "type": "people",
                        "id": "123"
                    }
                }
            }
        },
        {
            "type": "posts",
            "id": "321",
            "attributes": {
                "title": "Included objects",
                "body": "Yes, it is supported"
            },
            "relationships": {
                "author": {
                    "data": {
                        "type": "people",
                        "id": "123"
                    }
                },
                "comments": {
                    "data": [
                        {
                            "type": "comments",
                            "id": "456"
                        },
                        {
                            "type": "comments",
                            "id": "789"
                        }
                    ]
                }
            }
        }
    ]
}
...
```

**Comment by geniuscd** [comment]
Thank you, i will try to check it indeed. and i will reply back. maybe i was doing something wrong.

**Comment by geniuscd** [comment]
ok so what you need to do is add the "user.model" in order to get it in the included
thanks! now it worked following this link.
[Default include paths could be configured.](https://github.com/neomerx/json-api/blob/master/sample/Schemas/SiteSchema.php#L65-L72)
