### ISSUE TITLE
How to encode a whole tree with unknown depth

### ISSUE THREAD

**Issue by fbraem** [neomerx/json-api#165]
I have a model Category that can contain other categories as children. 'children' is defined as a relationship. When I add 'children' to the include paths, I only get the top-level categories with their direct children included. When I add 'children.children' to the include paths, I also get the grand children ... How can I be sure that all levels are included, because I don't know how deep the tree can be ...

This is the SchemaProvider for Category: https://github.com/tribbie/clubman/blob/develop/app/ADR/Categories/CategorySchema.php

**Comment by neomerx** [comment]
What you actually asking for is a parser which would follow only one relationship `children` for only one type `Category` to be parsed until an end is reached. I think it's possible though it's not typical usage and will require more than a couple of lines. Before we dive into this I'd suggest looking on this problem from a different angle and maybe you would be satisfied with simpler approach with very much the same result.

Just a reminder about json-api document structure. Suppose you have a root category(-ies) with other categories as children (nested or not). Then json-api document would have the following view
```
data:
  root element(s)
included:
 a flat list of other elements
```
Elements from flat list would have relationships (just `type` and `id`) which you would use to reconstruct nested data.

Thus as you would have to work with `flatten` data why not to flat the entire tree in the first place? In the final json the flat list would be moved to `data` section and no items would be in `included` section.

So it might look something like
```php
    function flatCategories(array $categories)
    {
        foreach ($categories as $category) {
            yield $category;
            foreach (flatCategories($category->children) as $childCategory) {
                yield $childCategory;
            }
        }
    }

    $result = $encoder->endodeData(flatCategories($categories));
```

**Comment by fbraem** [comment]
A flat tree works very well. Thanks!
