### ISSUE TITLE
"Meta" object is stripped from JSON response when using encodeError

### ISSUE THREAD

**Issue by blindbox** [neomerx/json-api#171]
Hi,

Version: v0.8.11

According to the JSON API spec, meta and errors top level objects can co-exist.

However, when trying out the test code below, the meta tag has been stripped, hence preventing a portion of the spec from being utilized.
```php
$encoded = Encoder::instance()->withMeta(['status' => false])
			->encodeError(new Error('Hello'));
```
`$encoded` gives me this JSON:
```json
{
  "errors": [
    {
      "id": "Hello"
    }
  ]
}
```

Trying out the same thing, but using encodeData works as expected.
```php
$encoded = Encoder::instance()->withMeta(['status' => true])
			->encodeData(null);
```
This returns:
```json
{
  "meta": {
    "status": true
  },
  "data": null
}
```

**Comment by neomerx** [comment]
Thanks for spotting it. According to the spec `errors` top-level can also co-exist with `jsonapi`.

**Comment by neomerx** [comment]
@blindbox Merged to `master`

**Comment by neomerx** [comment]
@blindbox released
