### ISSUE TITLE
Type of field status in class Document/Error

### ISSUE THREAD

**Issue by OskarsOzols** [neomerx/json-api#172]
While int and string are valid types for status argument in ctor of class Document/Error, it converts it to string as return type.

As I plan to use returned status as argument for http_response_code(), which accepts int - I wonder why it's transformed to string not int?

**Comment by lindyhopchris** [comment]
I suspect it's because the JSON API spec says this:

> status: the HTTP status code applicable to this problem, expressed as a string value.

**Comment by OskarsOzols** [comment]
Ok. Doesn't sound logic as all codes are numerals, but that's problem of specification.
