### ISSUE TITLE
Using 'type' as key in the scheme attributes will crash PHP

### ISSUE THREAD

**Issue by basz** [neomerx/json-api#176]
HI,

using 'type' as key in the scheme attributes will crash PHP.

    public function getAttributes($resource)
    {
        /* @var ProductGroupAttributeSetAttributeDTO $resource */
        return [
            'type'         => 'ddd', 
        ];
    }

Took me forever to find, but it turns out using 'type' is not possible. It will crash php fpm resulting in an internal server error. I don't think it is forbidden by the spec...

```
PHP 7.1.4-1+deb.sury.org~xenial+1 (cli) (built: Apr 11 2017 22:12:32) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.4-1+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by lindyhopchris** [comment]
> Fields for a resource object MUST share a common namespace with each other and with type and id. In other words, a resource can not have an attribute and relationship with the same name, nor can it have an attribute or relationship named type or id.

http://jsonapi.org/format/#document-resource-object-fields

**Comment by basz** [comment]
Ok Thanks.

But why does it crash and not throw an exception?

**Comment by lindyhopchris** [comment]
That is strange, it throws an Exception here:
https://github.com/neomerx/json-api/blob/master/src/Document/Presenters/ElementPresenter.php#L299-L304

Not sure why that would be causing a crash.

**Comment by basz** [comment]
I'll see if it gets there

**Comment by basz** [comment]
Ok my mistake - it does throw an exception... Thanks
