### ISSUE TITLE
Headers checker requires `Content-Type` header for requests without content

### ISSUE THREAD

**Issue by lindyhopchris** [neomerx/json-api#178]
According to the spec:

> Clients MUST send all JSON API data in request documents with the header Content-Type: application/vnd.api+json without any media type parameters.
http://jsonapi.org/format/#content-negotiation-clients

The key part here is that it says "data in request documents"... i.e. if you are not sending a request document, then there is no requirement to have a `Content-Type` header that matches a decoder. An example would be a `DELETE` request - no request document is sent, so the `Content-Type` header and matching to a decoder is irrelevant.

The implementation here:
https://github.com/neomerx/json-api/blob/master/src/Http/Headers/RestrictiveHeadersChecker.php#L47-L52

Does not follow the spec because it **always** checks the `Content-Type` header, regardless of whether a request document has been sent. This is resulting in errors on requests that do not send request documents.

Wondering what your thoughts on this are?

**Comment by neomerx** [comment]
@lindyhopchris Shall I expect a PR from you?

**Comment by lindyhopchris** [comment]
I'm more than happy to do a PR, but would be good to discuss how you want it solved. Unfortunately it's likely to be a breaking change because the `HeadersCheckerInterface` is going to have to change.

Possible solutions:

1. Pass the `ServerRequestInterface` into the `checkHeaders` method so the checker can decide whether it is going to check the content type header.
2. Pass a boolean into the `checkHeaders` method to say whether or not the `Content-Type` should be checked - something like `$didReceiveContent`

A non-breaking solution might be to introduce a new interface, e.g. `ContentNegotiatorInterface` and deprecate the `HeadersCheckerInterface`.

They are the ones that spring to mind but you might have other ideas?

**Comment by neomerx** [comment]
Created a new branch for experimenting with it. At least we can start with basic tests and look for options. I can start looking into it later today or tomorrow morning.

**Comment by neomerx** [comment]
The actual check is in lines [79-97](https://github.com/neomerx/json-api/blob/master/src/Http/Headers/RestrictiveHeadersChecker.php#L79-L97). With existing interfaces we can get the method (`GET`, `DELETE`, and etc) from `HeaderParametersInterface` and do not check the header for some methods.

```php
        if ($parameters->getMethod() === 'DELETE') {
            return;
        }
```
The next option could be adding `hasBody(): bool` method to `HeaderParametersInterface` in order to do the check.

What's your opinion on that?

**UPD** the `$parameters` is created at [a place](https://github.com/neomerx/json-api/blob/master/src/Http/Headers/HeaderParametersParser.php#L73) where we have `ServerRequestInterface` so it should be a trivial as well.

**Comment by lindyhopchris** [comment]
We can't just use the HTTP method. For a request to remove an id from a has-many relationship, `DELETE` is used with body content. The example in the spec is:

```http
DELETE /articles/1/relationships/comments HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": [
    { "type": "comments", "id": "12" },
    { "type": "comments", "id": "13" }
  ]
}
```

However a `DELETE` of the resource itself, i.e. `DELETE /articles/1` does not have content. So I think we're going to need to detect if HTTP request body content has been sent, and check the content type if it has.

For info, because the JSON API spec also defines the HTTP requests that can be sent by a client, my extension library has a `RequestInterpreterInterface` for analysing the client request, which has an `isExpectingDocument()` method on it to check if the spec says that a document should have been sent by the client:
https://github.com/cloudcreativity/json-api/blob/master/src/Contracts/Http/Requests/RequestInterpreterInterface.php#L163-L175

**Comment by neomerx** [comment]
The first step is made. The check for content type header will be executed if the request has a body. On [this](https://github.com/neomerx/json-api/blob/feature/issue178/src/Http/Headers/HeaderParametersParser.php#L57) line.

**Comment by neomerx** [comment]
@lindyhopchris I'm planning to check presence of the body with

```php
        $hasBody = $request->getParsedBody() !== null;
```

Can you add a test for your usage case while I'm adding changes to make this line not fail with built-in wrappers?

**Comment by lindyhopchris** [comment]
I've added some comments to the commit. This looks like it will work, but I really think `hasBody` is a strange method on an interface about headers as the body has nothing to do with headers. The interface says that the `getContentTypeHeader()` will return null if there is no body, so I don't see the point of the `hasBody` method.

Yes I can add tests but can't immediately - maybe this afternoon.

**Comment by neomerx** [comment]
I removed `hasBody` and check content type for `null` instead.

**Comment by neomerx** [comment]
@lindyhopchris Added usage of `getParsedBody` and fixed broken tests. Next step would be adding your test(s) and make sure of full test coverage.

**Comment by lindyhopchris** [comment]
@neomerx I've pushed a commit with some additional tests in it.

I need to however do some extra research. `getParsedBody` is returning an empty array in the `ServerRequestInterface` that Laravel uses rather than `null`. I'll need to take a look at a couple of server request libraries to see what their logic is for returning `null`. Will get back to you...

**Comment by lindyhopchris** [comment]
Ok, so here's what the HTTP spec says:

> The presence of a message-body in a request is signaled by the inclusion of a Content-Length or Transfer-Encoding header field in the request's message-headers. A message-body MUST NOT be included in a request if the specification of the request method (section 5.1.1) does not allow sending an entity-body in requests. A server SHOULD read and forward a message-body on any request; if the request method does not include defined semantics for an entity-body, then the message-body SHOULD be ignored when handling the request.
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.3

Looking at the PSR implementations (Zend and Guzzle) I think we can't rely on `getParsedBody` returning `null`, not least because the above does say that the server should "forward a message body on any request". However, the above tells us we should ignore the message body if the semantics are not included, i.e. there is no Content-Length or Transfer-Encoding header.

**Comment by neomerx** [comment]
I believe it's totally OK to rely on the method because HTTP spec not relevant for PSR implementation and PSR itself clearly states

> A null value indicates the absence of body content.

```php
    /**
     * Retrieve any parameters provided in the request body.
     *
     * If the request Content-Type is either application/x-www-form-urlencoded
     * or multipart/form-data, and the request method is POST, this method MUST
     * return the contents of $_POST.
     *
     * Otherwise, this method may return any results of deserializing
     * the request body content; as parsing returns structured content, the
     * potential types MUST be arrays or objects only. A null value indicates
     * the absence of body content.
     *
     * @return null|array|object The deserialized body parameters, if any.
     *     These will typically be an array or object.
     */
    public function getParsedBody();
```

**Comment by neomerx** [comment]
@lindyhopchris  I merged it into `develop` and it only waits for your feedback.

**Comment by neomerx** [comment]
@lindyhopchris ping

**Comment by lindyhopchris** [comment]
Sorry, no reply over the weekend as I wasn't working.

Not sure what you want me to feedback on. Looking through the PSR implementations, this won't work.

The PSR interface says that if not returning the `_POST` variables

> this method **may** return any results of deserializing

As a PSR package won't know how to parse a request body that was not provided as a `_POST`, there's a real risk that even if I convince the packages to change their implementation, that they return `null` when they don't know how to parse the body content. Seeing as the interface doesn't specify that they **must** attempt to deserialize the content, they don't have to attempt to deserialize it.

**Comment by lindyhopchris** [comment]
I suppose my point is *we* know how to parse the body content, so why are we relying on a method that needs to know how to parse something to give us an accurate answer? We'll get a more accurate answer relying on the actual request properties rather than a parsing method.

**Comment by neomerx** [comment]
I tried it with `Diactoros`. It returns an empty array in `getParsedBody` for `DELETE` request even when no actual body was sent.

So it looks we have to move to plan B. What's your suggestion for the method?

I think if we add a default parameter called `$checkContentType = true` (or just another method with such signature) it will be a solution.

**Comment by neomerx** [comment]
@lindyhopchris proposed solution is in `issue178` branch

**Comment by lindyhopchris** [comment]
Yes, plan B was definitely my feeling too!

I think adding a `checkContentType` argument makes sense. I'll give this a go in Laravel and let you know - my gut feeling is this will work.

**Comment by neomerx** [comment]
@lindyhopchris I've been waiting for your feedback for some time before merging to `master`. Let me know if you want to have any corrections before it's tagged and released tomorrow.

**Comment by lindyhopchris** [comment]
@neomerx sorry, busy week at work.

Yes, this all looks good. Where I'm parsing the headers I'll be able to pass in a `checkContentType` boolean so this will fix the problem. Thanks!
