### ISSUE TITLE
composer installs only vendor folder.

### ISSUE THREAD

**Issue by yairpe** [neomerx/json-api#180]
composer installs only vendor folder.
Sample app cannot be found

I had to clone it via git to get the sample app files

**Comment by neomerx** [comment]
@yairpe Yes, it's done on purpose to minimize installation. Development files such as tests, samples, Travis configs and etc are not included in the install. The full list of excluded files could be found in https://github.com/neomerx/json-api/blob/master/.gitattributes

**Comment by neomerx** [comment]
@yairpe I feel I have answered the question. If you have any further questions please don't hesitate to ask.
