### ISSUE TITLE
Parsers for HTTP Query and Headers should provide more error details on invalid inputs

### ISSUE THREAD

**Issue by neomerx** [neomerx/json-api#185]
Currently, for invalid values in HTTP headers and queries, it throws an exception without any details.

It should provide some related info such as description and parameter name.

This issue is created from [this comment](https://github.com/neomerx/json-api/issues/184#issuecomment-329090943).

**Comment by lindyhopchris** [comment]
This is a great change, been meaning to ask for it for a while.

Can the `createInvalidQueryErrors()` and `createParamErrors()` methods be `protected` instead of `private`? This would allow the class to be extended and just those methods overriden to allow custom errors to be returned?

**Comment by neomerx** [comment]
@lindyhopchris done

**Comment by neomerx** [comment]
released in 1.0.5
