### ISSUE TITLE
What if I want to map an interface to a Schema

### ISSUE THREAD

**Issue by d-lamers** [neomerx/json-api#192]
I have been implementing this package and it already feels really robust. But I have one thing that bothered me. If I have a Model class which implements a specific interface which I want a default schema for. I need to give the `Container` every class of which implements that interface and then assign the same `Schema` for all. Wouldn't this be much easier if I could just say to the `Container` if we use this interface use this schema. No matter what type of instance implementing that interface I throw at it.

**Comment by neomerx** [comment]
Hi,

Sorry, I haven't got the idea. Could you please illustrate it with a 
basic code sample?

**Comment by neomerx** [comment]
After re-reading it a few times I think I'm starting to understand it.

You want to the container to work something like
- check if there is any mapping for the given instance's class
- if no match found it should check if instance implements specific 
interface(s) and if it does the container has special mapping for such 
cases. Looks like models would have a default Scheme if no specific 
Scheme is bind.

I don't have a quick reply at the moment until I'm back from vacation 
early next week. I need my dev working environment so I can look the 
question closer.

**Comment by d-lamers** [comment]
Sorry if I wasn't very clear, but that is indeed exactly what I meant. I think it could be really useful like that. Take an Eloquent model for example if you're a Laravel developer. One schema could easily parse any kind of Eloquent model.

**Comment by bravo-kernel** [comment]
@d-lamers, you might want to take a look at this CakePHP generic schema for inspiration, it does exactly what you describe.  

https://github.com/FriendsOfCake/crud-json-api/blob/master/src/Schema/JsonApi/DynamicEntitySchema.php

**Comment by d-lamers** [comment]
Good suggestion and that’s a fine solution. Kinda what I’m doing right now. I dont know cakephp but I suppose you extend the Entity class for each model? So like my case you’d  still have to let the Container know for each type of `\Cake\ORM\Entity` it should use that schema.

**Comment by bravo-kernel** [comment]
It first checks if a specific schema is available for the entity. If it 
does not exist, it uses this dynamic entity schema.

There is no need for extending the/any Model, everything is 
auto-detected.

------ Original Message ------

**Comment by d-lamers** [comment]
Sorry I think I'm not getting it.

I don't know CakePHP but say you have an `Enitity` abstraction or interface. Which you extend or implement in your models say `UserModel`.
How does CakePHP tell the container to parse any `Model` say `UserModel` to use this dynamic entity schema. How is the `DynamicEntitySchema` assigned to the `Container` for all these models. Because that does not seem to be possible? I think I'm missing that point here.

I made my own kind of dynamic schema for my interface. But I need to assign all classes that implement it to the `Container` to my dynamic schema.

**Comment by neomerx** [comment]
@d-lamers You can replace any part of the library with your custom implementation. Having custom container will be a straightforward path to meet your demands. Here is [an example of how to replace Container](https://github.com/neomerx/json-api/tree/master/tests/Extensions/Issue154). With a custom container, any logic could be implemented.

Note: The example above shows how to replace the container implementation. The actual implementation is just reused from the standard one. Though it's only 3 simple methods to implement.

**Comment by neomerx** [comment]
This [wiki](https://github.com/neomerx/json-api/wiki/Extending-Encoder#package-extension) will also be useful for understanding. Anyways, feel free to ask any further questions.

**Comment by d-lamers** [comment]
Was keeping this as an option, but will indeed start working on a custom implementation then.

**Comment by neomerx** [comment]
To sum up the idea of customization shortly. Instead of having many points/ways of replacing default parts there is one replaceable object that creates all objects in the library - `Factory`. So in addition to custom parts (e.g. Container) you need `Factory` that creates your custom objects. Thus the factory typically consists of one or more 1 line methods.

Next step to actually inject that factory into Encoder. This is also 1 line method where you replace default factory with your custom one.

**Comment by neomerx** [comment]
I believe it could be a starting point for your custom container

```php
use Neomerx\JsonApi\Contracts\Schema\ContainerInterface;
use Neomerx\JsonApi\Contracts\Schema\SchemaFactoryInterface;
use Neomerx\JsonApi\Contracts\Schema\SchemaProviderInterface;

class CustomContainer implements ContainerInterface
{

    /**
     * @var SchemaFactoryInterface
     */
    private $factory;

    /**
     * @param SchemaFactoryInterface $factory
     */
    public function __construct(SchemaFactoryInterface $factory)
    {
        $this->factory = $factory;
    }

    /**
     * @inheritdoc
     */
    public function getSchema($resourceObject): ?SchemaProviderInterface
    {
        return $this->getSchemaByType(get_class($resourceObject));
    }

    /**
     * @inheritdoc
     */
    public function getSchemaByType(string $type): SchemaProviderInterface
    {
        $mappings  = [
            'App\Models\Comment' => 'App\Providers\CommentProvider',
            'App\Models\Post'    => 'App\Providers\PostProvider',
        ];
        $className = $mappings[$type] ?? 'App\Providers\DefaultProvider';

        return $this->getProviderByClassName($className);
    }

    /**
     * @inheritdoc
     */
    public function getSchemaByResourceType(string $resourceType): SchemaProviderInterface
    {
        $mappings  = [
            'comments' => 'App\Providers\CommentProvider',
            'posts'    => 'App\Providers\PostProvider',
        ];
        $className = $mappings[$resourceType] ?? 'App\Providers\DefaultProvider';

        return $this->getProviderByClassName($className);
    }

    /**
     * @param string $className
     *
     * @return SchemaProviderInterface
     */
    private function getProviderByClassName(string $className): SchemaProviderInterface
    {
        // Though I would strongly recommend to cache provider instances.
        return new $className($this->factory);
    }
}
```
