### ISSUE TITLE
Schema provides all attributes, even if not all are being encoded.

### ISSUE THREAD

**Issue by lindyhopchris** [neomerx/json-api#195]
Maybe something for v2 as this is breaking. It stems from this issue:
https://github.com/cloudcreativity/laravel-json-api/issues/136

At the moment the SchemaProviderInterface::getAttributes() will return all resource attributes, even if not all of them are being encoded (i.e. if the `fields` parameter has specified that only some should be included). 

If you have an attribute that is costly to calculate, you have no way of knowing you don't need to do the calculation because the method isn't provided with the fields parameter.

It would be useful if the `getAttributes` method is given the information to know whether it needs to calculate an attribute, along the lines of `$includeRelationships` in the `getRelationships` method.

Probably something for v2 as changing the interface would be breaking?

**Comment by neomerx** [comment]
Please have a look.

**Comment by neomerx** [comment]
`getRelationships` now also receive information about fields filtering though I'm not entirely sure that it's actually used atm. Thus it needs some additional testing for combinations of include paths and relationship fieldsets.

**Comment by lindyhopchris** [comment]
Yeah looks ok. I'm guessing the encoder will still filter the attributes by the fields, so that in the schema you're under no obligation to exclude attributes yourself. You can just choose to not do it if you want.

Also, it's really useful in the relationships method that you can just do `isset($includeRelationships['foo'])`. Will this be the same with the fields array or will you need to do `in_array('foo', $fields)`?

**Comment by neomerx** [comment]
Both `includes` and `fieldsets` come from user input. Includes instruct the parser to actually go for specific paths and fieldsets to filter what comes out of this.

Also, I can answer my own question: 'Thus it needs some additional testing for combinations of include paths and relationship fieldsets.' If a path is not included it won't show anyways for further filtering.

An answer to your question would be "If a user hasn't asked to include a path it shouldn't appear neither in `$includeRelationships` nor in `$fieldKeysFilter`". Thus there is not much sense to add `$fieldKeysFilter` to `getRelationships`.

**Comment by neomerx** [comment]
Removed `$fieldKeysFilter` for relationships. Now it looks finished.

**Comment by lindyhopchris** [comment]
Reopened this because the problem has been re-introduced in `v3` by removing the `$fieldKeysFilter` from the `getAttributes()` method.

**Comment by neomerx** [comment]
The lib has no implementation of `SchemaInterface`. It's on developer's side and they are free to implenent it the way they wish.

@lindyhopchris Can you please tone down a bit? I'm closing the issue because currently, it duplicates #236  :fire:
