### ISSUE TITLE
BaseQueryParser generators problems

### ISSUE THREAD

**Issue by juliangut** [neomerx/json-api#198]
About the extensive use of generators in BaseQueryParser

```php
if ($queryParameters instanceof BaseQueryParserInterface) {
                $encodingParameters = new EncodingParameters(
                    $queryParameters->getIncludes(),
                    $queryParameters->getFields()
                );
            }
```
Produces "TypeError: Argument 1 passed to Neomerx\\JsonApi\\Encoder\\Parameters\\EncodingParameters::__construct() must be of the type array or null, object given" because indeed they are \Generator instances and not an arrays

This can be solved by transforming \Generator to an array

```php
if ($queryParameters instanceof BaseQueryParserInterface) {
                $encodingParameters = new EncodingParameters(
                    \iterator_to_array($queryParameters->getIncludes()),
                    \iterator_to_array($queryParameters->getFields())
                );
            }
```

But this solution produces further problems because resulting array looses "resource key" and then when using fields in [getFieldSet](https://github.com/neomerx/json-api/blob/master/src/Encoder/Parameters/EncodingParameters.php#L68) it always returns null

In the same fashion when traversing relationships to be included to response in getIncludeRelationships $includePaths are \Generator instances and thus [getRelationshipNameForTopResource](https://github.com/neomerx/json-api/blob/master/src/Encoder/Parameters/ParametersAnalyzer.php#L114) produces a Type error expecting an string

Generators are a great thing but they cannot be just dropped into a codebase, they need to be integrated with care at all levels (they are not really arrays and don't behave like them), in this scenario means taking care of [EncodingParameters](https://github.com/neomerx/json-api/blob/master/src/Encoder/Parameters/EncodingParameters.php#L41) constructor and how getFieldSet method works at the very least, I haven't gone any further than this so I don't know if problems spread more

In the mean time I'm creating a custom implementation of BaseQueryParserInterface based on array usage

**Comment by neomerx** [comment]
Using this helper is absolutely not mandatory. The main functionality of encoding do not depend on this class.

Thank you for looking the code closer and trying it in various use cases. You obviously have some sample code you're working with. Could you please share it so it would be easier to improve flexibility of `BaseQueryParser`?

**Comment by juliangut** [comment]
Hi

I know BaseQueryParser usage is not mandatory but I'd expect it to work at least

About the code I've just pushed the initial release of the library I'm working on so you can have a look (still missing several functionalities I'd like to add) https://github.com/juliangut/json-api

**Comment by neomerx** [comment]
`BaseQueryParser` is designed to be used as a base class for custom query parsers. The reason why it's not possible to include 'full' implementation is that JSON API spec does not define filters and pagination parameters. So it's up to a developer. Though `BaseQueryParser` can provide parsing for fieldsets, includes and sorts. Also, child classes might add additional functionality such as input data validation.

> I know BaseQueryParser usage is not mandatory but I'd expect it to work at least

I've prepared a test example that shows it works. The mains steps of the test are:
- Define [input query parameters](https://github.com/neomerx/json-api/blob/7d5e51f22c298ff858626f966a1a035d41d557fc/tests/Http/Query/BaseQueryParserTest.php#L229-L237) in a format that comes from `Request`
- Define a [parser class](https://github.com/neomerx/json-api/blob/7d5e51f22c298ff858626f966a1a035d41d557fc/tests/Http/Query/BaseQueryParserTest.php#L239-L310) that extends `BaseQueryParser`
- [Check the inputs was parsed successfully](https://github.com/neomerx/json-api/blob/7d5e51f22c298ff858626f966a1a035d41d557fc/tests/Http/Query/BaseQueryParserTest.php#L313-L325)

At this stage, the parsed data are ready to be used for `EncodingParameters`. As you said you had issues with going further I've added a few more steps to use for actual encoding
- [Define some data for encoding](https://github.com/neomerx/json-api/blob/7d5e51f22c298ff858626f966a1a035d41d557fc/tests/Http/Query/BaseQueryParserTest.php#L332-L337)
- [Do actual encoding to JSON API](https://github.com/neomerx/json-api/blob/7d5e51f22c298ff858626f966a1a035d41d557fc/tests/Http/Query/BaseQueryParserTest.php#L340-L344)
- [Check the result](https://github.com/neomerx/json-api/blob/7d5e51f22c298ff858626f966a1a035d41d557fc/tests/Http/Query/BaseQueryParserTest.php#L346-L394)

I have a feeling that I've answered the question and going to close the issue. If you have any further questions please do not hesitate to ask.
