### ISSUE TITLE
Relationships specific interaction

### ISSUE THREAD

**Issue by designermonkey** [neomerx/json-api#205]
This is a question more than an issue.

Based on `http://jsonapi.org/format/#crud-updating-relationships` do you have any examples on how I would return the simple data returned by these `/relationships` endpoints?

**Comment by designermonkey** [comment]
Answering my own question ;)

https://github.com/neomerx/json-api/blob/master/tests/Encoder/EncodeSimpleObjectsTest.php#L269

**Comment by neomerx** [comment]
Yay, you're of a very few devs who actually look samples in tests :wink: 1337

**Comment by designermonkey** [comment]
But that's the documentation right?? :D
