### ISSUE TITLE
Access to private method in trait src/Http/Query/BaseQueryParserTrait.php

### ISSUE THREAD

**Issue by freddiegar** [neomerx/json-api#208]
splitCommaSeparatedStringAndCheckNoEmpties method is private, then I get this error:

Call to private method Neomerx\JsonApi\Http\Query\BaseQueryParser::splitCommaSeparatedStringAndCheckNoEmpties() from context 'Limoncello\Flute\Http\Query\QueryParser' in /var/www/html/vendor/limoncello-php/flute/src/Http/Query/QueryParser.php:461

**php -v**
PHP 7.1.14 (cli) (built: Feb  7 2018 00:40:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by freddiegar** [comment]
Additional info: This error was found while I used filter parameters in request using [Flute](https://github.com/limoncello-php/framework/tree/master/components/Flute) , thus:

/posts?filter[status][eq]=3

I am using version: 
json-api: 2.0.4
flute: dev-master

Thanks, really is a great package!

**Comment by neomerx** [comment]
Thanks. Sorry for the bug. I've already fixed it for limoncello 0.9.x. It will take me some time to apply it to 0.8.x and release. You are using 0.8.x, aren't you?

**Comment by neomerx** [comment]
@freddiegar Should be fixed for both branches. Please have a look and let me know.

**Comment by freddiegar** [comment]
Perfect, let me check it!

**Comment by freddiegar** [comment]
Now work it, thanks so much!
