### ISSUE TITLE
Deep relations

### ISSUE THREAD

**Issue by Dylan-DutchAndBold** [neomerx/json-api#212]
Is there a way to define deeply nested relations? In my case I'm building a file explorer and I have a deep nest of directories with files. So every resource of `directory` has the relation of `directory` and `file` I want these to be fully returned in one request.

**Comment by neomerx** [comment]
Sure. You can pass a list of include paths in `EncodingParameters` on encoding (sample [here](https://github.com/neomerx/json-api/wiki#encoding)).

If encoding of deeply nested objects is a typical task in your application and you feel that include paths preparation is an unnecessary burden, you may consider [replacing](https://github.com/neomerx/json-api/wiki/Extending-Encoder#package-extension) method [ParserManagerInterface::isShouldParseRelationships](https://github.com/neomerx/json-api/blob/5229bb52888aba8fcfabf923fbaabd6f7aedd74a/src/Contracts/Encoder/Parser/ParserManagerInterface.php#L33) with a method that simply returns `true`.

**Comment by neomerx** [comment]
I have a feeling I've answered the question. If you have any further questions please don't hesitate to ask.

**Comment by Dylan-DutchAndBold** [comment]
Awesome answer thanks
