### ISSUE TITLE
Is v3 produciton ready?

### ISSUE THREAD

**Issue by PabloKowalczyk** [neomerx/json-api#222]
Hello, yesterday you published version `3.0.0` (BTW performance increase looks very good), but this release is marked as "Pre-release" on GitHub, but for composer (packagist) it is stable release. Also version number `v3.0.0` looks like stable.
It this version ready for production use or not?

**Comment by neomerx** [comment]
**Long Answer**
V3 Passes all JSON API encoding tests that pass V2 and has 100% test coverage. So it looks at least as good as V2. [Scrutinizer also likes the new code.](https://scrutinizer-ci.com/g/neomerx/json-api/?branch=develop) So why it's **pre-released**? There are two reasons
- Feedback from developers needed. I'm going to switch (and check) a few projects to V3.
- JSON API 1.1 officially is not released yet, so early February is the earliest V3 can be released.

**Short Answer**
No, not yet. It's planned to be released in early February. I would appreciate if you try the pre-release version and provide some positive/negative/mixed feedback.

**Comment by PabloKowalczyk** [comment]
Now i get it. IMHO You should release `v3.0.0-rc.1` first, collect feedback and/or fix bugs and then release stable `v3.0.0`.

> I would appreciate if you try the pre-release version and provide some positive/negative/mixed feedback.

I will.

Thanks.

**Comment by neomerx** [comment]
renamed to `v3.0.0-rc.1`

**Comment by PabloKowalczyk** [comment]
Now everything is clear for me.

**Comment by neomerx** [comment]
released [v3.0.0](https://github.com/neomerx/json-api/releases/tag/v3.0.0)

**Comment by PabloKowalczyk** [comment]
Nice one :tada: Thanks!
