### ISSUE TITLE
Allow getting encoded data as array (instead of json string)

### ISSUE THREAD

**Issue by Ilyes512** [neomerx/json-api#223]
I was using version 2 and I am now in the process of upgrading to version 3. What I would like to do is get the (build) data as array instead of (encoded) json string.

```php
    /**
     * @inheritdoc
     */
    public function encodeData($data): string
    {
        // encode to json
        $array  = $this->encodeDataToArray($data);
        $result = $this->encodeToJson($array);

        $this->resetPropertiesToDefaults();

        return $result;
    }
```

So I would like to call `$this->encodeDataToArray($data)` directly (it's visibility is now set to protected).

Further I see that you call `$this->resetPropertiesToDefaults();` which seems a bit strange cause it also resets urlprefix, encodeoptions and encodedepth. At this point every request only calls `encodeData` (or `encodeDataAsArray`) only once, but who know's what happens in the future.

At the moment I am extending the (Extended)Encoder class and I just added a `encodeDataAsArray` method that calls `encodeDataToArray`. I find this quite ugly (would like to use the `encodeDataToArray` name).

I also tried to "fix" the reset by adding this:

```php
    private function resetPropertiesToDefaults(): self
    {
        return $this->reset(
            $this->getUrlPrefix() ?? static::DEFAULT_URL_PREFIX,
            static::DEFAULT_INCLUDE_PATHS,
            static::DEFAULT_FIELD_SET_FILTERS,
            $this->getEncodeOptions() ?? static::DEFAULT_JSON_ENCODE_OPTIONS,
            $this->getEncodeDepth() ?? static::DEFAULT_JSON_ENCODE_DEPTH
        );
    }
```

Until I noticed it is private... so this is not going to work. This would be solved by either changing it's visibility to protected or make the call to resetPropertiesToDefaults() optional.
(I could also solve it by overwriting `encodeData()`. This solution popped up while writing this issue :P)

**Comment by neomerx** [comment]
The requirement to encode to an array is not new. It comes from #169. So encoding methods are intentionally made short and containing major steps which could be reused and combined depending on the usage requirements.

The [testing code for this extension was migrated to v3](https://github.com/neomerx/json-api/tree/develop/tests/Extensions/Issue169).

I'll think again if reset feature could be done better, but you've already got everything you need to tailor it to your needs ;)

**Comment by Ilyes512** [comment]
Cool... 

Also did not thought about creating a custom extended factory class :)

**Comment by neomerx** [comment]
Everything (or almost everything) is created via the factory, so you can inject your custom encoders, schemas/schema containers (for example, to store schemas in the database or cache), and etc.

I'll keep it open for a while.

**Comment by neomerx** [comment]
I've added a method `reset` to the encoder interface and got rid of `resetPropertiesToDefaults`. Thus encoder settings such as prefix, links, meta and etc could be reused between calls.

**Comment by Ilyes512** [comment]
> I've added a method `reset` to the encoder interface and got rid of `resetPropertiesToDefaults`. Thus encoder settings such as prefix, links, meta and etc could be reused between calls.

Nice, I will implement it as soon as there is a new tag that includes the changes :)

**Comment by neomerx** [comment]
released as `v3.0.0-rc.3`

**Comment by neomerx** [comment]
released as [v3.0.0](https://github.com/neomerx/json-api/releases/tag/v3.0.0)

**Comment by Ilyes512** [comment]
I am trying out the changes now... 

When overwriting the reset() method I can't change the class properties (links, profile, hasMeta, etc) directly because they are private. I could use the set methods if changing the properties visibility to protected is a problem?:

```php
    /**
     * Reset to initial state.
     *
     * @param string   $urlPrefix
     * @param iterable $includePaths
     * @param array    $fieldSets
     * @param int      $encodeOptions
     * @param int      $encodeDepth
     *
     * @return self|EncoderInterface
     */
    public function reset(
        string $urlPrefix = Encoder::DEFAULT_URL_PREFIX,
        iterable $includePaths = Encoder::DEFAULT_INCLUDE_PATHS,
        array $fieldSets = Encoder::DEFAULT_FIELD_SET_FILTERS,
        int $encodeOptions = Encoder::DEFAULT_JSON_ENCODE_OPTIONS,
        int $encodeDepth = Encoder::DEFAULT_JSON_ENCODE_DEPTH
    ): EncoderInterface {
        $this->links          = null;
        $this->profile        = null;
        $this->hasMeta        = false;
        $this->meta           = null;
        $this->jsonApiVersion = null;
        $this->jsonApiMeta    = null;
        $this->hasJsonApiMeta = false;

        $this
            ->withUrlPrefix($urlPrefix)
            ->withIncludedPaths($includePaths)
            ->withFieldSets($fieldSets)
            ->withEncodeOptions($encodeOptions)
            ->withEncodeDepth($encodeDepth);

        return $this;
    }
```

**Comment by Ilyes512** [comment]
Resetting links is currently not possible:

```php
    /**
     * @param iterable $links
     *
     * @return self|EncoderInterface
     */
    public function withLinks(iterable $links): EncoderInterface
    {
        $this->links = $this->hasLinks() === false ?
            $links :
            $this->links = array_merge(
                $this->iterableToArray($this->getLinks()),
                $this->iterableToArray($links)
            );

        return $this;
    }

    /**
     * @return bool
     */
    protected function hasLinks(): bool
    {
        return $this->links !== null;
    }
```

With `withLinks` only accepting an iterable I can only pass it an empty [], but then `hasLinks` would return true instead of false.

**Comment by Ilyes512** [comment]
In my case I solved it with:

```php
    /**
     * Reset to initial state.
     *
     * @param string   $urlPrefix
     * @param iterable $includePaths
     * @param array    $fieldSets
     * @param int      $encodeOptions
     * @param int      $encodeDepth
     *
     * @return self|EncoderInterface
     */
    public function reset(
        string $urlPrefix = Encoder::DEFAULT_URL_PREFIX,
        iterable $includePaths = Encoder::DEFAULT_INCLUDE_PATHS,
        array $fieldSets = Encoder::DEFAULT_FIELD_SET_FILTERS,
        int $encodeOptions = Encoder::DEFAULT_JSON_ENCODE_OPTIONS,
        int $encodeDepth = Encoder::DEFAULT_JSON_ENCODE_DEPTH
    ): EncoderInterface {
        return parent::reset(
            $this->getUrlPrefix() ?? static::DEFAULT_URL_PREFIX,
            static::DEFAULT_INCLUDE_PATHS,
            static::DEFAULT_FIELD_SET_FILTERS,
            $this->getEncodeOptions() ?? static::DEFAULT_JSON_ENCODE_OPTIONS,
            $this->getEncodeDepth() ?? static::DEFAULT_JSON_ENCODE_DEPTH
        );
    }
```

But it would still be nice to be able to not reset `$this->jsonApiVersion = null;`, `$this->jsonApiMeta    = null;` and `$this->hasJsonApiMeta = false;`.

**Comment by neomerx** [comment]
> Further I see that you call `$this->resetPropertiesToDefaults();` which seems a bit strange cause it also resets urlprefix, encodeoptions and encodedepth.

It's probably lost somewhere in the discussion, but `reset` is not called currently in `encodeXXX` methods. So you probably do not need to do things you do with `reset()`.

**Comment by Ilyes512** [comment]
Yes, I know. But I do want to use reset, but slightly adjusted.

**Comment by neomerx** [comment]
What kind of changes and functionality do you need for reset?

**Comment by Ilyes512** [comment]
The reset() method also resets the (private) class parameters, see https://github.com/neomerx/json-api/blob/master/src/Encoder/EncoderPropertiesTrait.php#L120-L126.

I would have been easy to do the same. One can still fix it, but with a little more code. So you can ignore my comments above.

**Comment by neomerx** [comment]
OK, let me know if you want me to add any changes.
