### ISSUE TITLE
subUrl property is private - BaseSchema

### ISSUE THREAD

**Issue by Munsio** [neomerx/json-api#240]
Due to the visibility of the property `$subUrl` in the BaseSchema it is not possible to overwrite it in the self implemented Schema itself.

https://github.com/neomerx/json-api/blob/master/src/Schema/BaseSchema.php#L40

Is this intended or should this property be `protected` instead?
Or is there something i miss?

**Comment by neomerx** [comment]
Yes, it's done intentionally because URLs typically have a certain format and the field you refer to is a caching field.

You can overwrite method [getResourcesSubUrl](https://github.com/neomerx/json-api/blob/7a64109c4d1f1be2484906e6194b0898e6ea99e0/src/Schema/BaseSchema.php#L157-L164) if you want subUrl to be composed in a different way.

**Comment by Munsio** [comment]
Okay.
So then the if construct where subUrl gets checked if it is null is unnecessary cause there is no setter for subUrl, and to the nature of private there is no possibility to assign any value to it.
In fact the subUrl property can be removed - am i right?

**Comment by neomerx** [comment]
If you want `getResourcesSubUrl` behave differently you will need to override it. Feel free to add any new `protected` or `private` fields.

Also, you don't have to inherit from `BaseSchema` and can implement `SchemaInterface` from scratch. That would be only a few tens of lines and `BaseSchema` is a good starting point.

**Comment by Munsio** [comment]
I think that we got carried away a little.

I know that i can override `getResourcesSubUrl` if i want to change the behaviour and also that i can implement my own `BaseSchema` which implements `SchemaInterface`.

But i am talking about the current implementation of `BaseSchema` which contains a private property without any setter for it, which implies that the value of this property can never change and therefore will always be `null`.
Which leads that the current implementation of `getResourcesSubUrl` in the BaseSchema can be broken down to a simple

```
    /**
     * Get resources sub-URL.
     *
     * @return string
     */
    protected function getResourcesSubUrl(): string
    {
        return '/' . $this->getType();
    }
```
and in addition the property `subUrl` can be removed cause it is never be used.

On the other hand if `subUrl` in the BaseSchema get its visibility changed from `private` to `protected` everyone who extends `BaseSchema` can set it in their Schema class and therefore the current implementation of `getResourcesSubUrl` in the `BaseSchema` makes sense.

**Comment by neomerx** [comment]
> But i am talking about the current implementation of `BaseSchema` which contains a private property without any setter for it, which implies that the value of this property can never change and therefore will always be `null`.

What do you think [this line](https://github.com/neomerx/json-api/blob/7a64109c4d1f1be2484906e6194b0898e6ea99e0/src/Schema/BaseSchema.php#L160) does?

**Comment by Munsio** [comment]
ahh - thats why you are referring to it as `caching` variable.

Ok then nvm - i will close this issue.
All questions answered - Thanks
