### ISSUE TITLE
[Question] How to exclude relationships on collections by default?

### ISSUE THREAD

**Issue by nanawel** [neomerx/json-api#241]
Hi,
First of all, thank you very much for your lib. It eases a lot the implementation of a JSON-API compliant server application.

Next, I'd like to know if it's possible (and how) to exclude **by default** (= when there is no `?include=` query parameter) relationships on the items of a collection, when it's the primary data.
The reason is quite obvious: retrieveing those data can be very resource-consuming and so the client has to explicitly specified he wants them - and which - when retrieving a collection.

I've thought of extending `FieldSetFilter` but:
- it works as a *whitelist*, and I'd prefer a *blacklist*
- it knows which type of resource is processed, but not its level in the returned structure

**Comment by neomerx** [comment]
For example, you may return what you have. If you have full data for a relationship return full data. If you have an only ID (e.g. author_id) then return only the ID and if you have nothing then return just link to the relationship.

In [this example](https://github.com/neomerx/json-api/blob/7a64109c4d1f1be2484906e6194b0898e6ea99e0/tests/Data/Schemas/PostSchema.php#L69-L74) it checks actual data in the object and returns either full `Author` resource or just a link. Also, if you have only ID (e.g. author_id ), you can return only ID with `IdentifierInterface` like in the example [here](https://github.com/neomerx/json-api/blob/7a64109c4d1f1be2484906e6194b0898e6ea99e0/tests/Encoder/EncodeSimpleObjectsTest.php#L1098-L1140).

If you want even more advanced things like on-demand deciding if resources should be uploaded from your database it's possible but difficult as you will need to know in your schema what are the filters and include paths in the encoder that calls your schemas. There are some ideas on how to make it easier so let me know if you go this route.

**Comment by nanawel** [comment]
Hi @neomerx, thanks for your response.

> For example, you may return what you have. If you have full data for a relationship return full data. If you have an only ID (e.g. author_id) then return only the ID and if you have nothing then return just link to the relationship.

That's not possible because I virtually have all data when I process the schema. What I don't know is whether I should include them or not.

> If you want even more advanced things like on-demand deciding if resources should be uploaded from your database it's possible but difficult as you will need to know in your schema what are the filters and include paths in the encoder that calls your schemas. There are some ideas on how to make it easier so let me know if you go this route.

I think I'll have to investigate this way. I may go with the `FieldSetFilter` like I said, but I'll need to tune it a little bit. What's problematic anyway is that I might need to create a sub-interface of `\Neomerx\JsonApi\Contracts\Encoder\EncoderInterface` to add the `with*` method(s) I need. And with it, a subclass that implements its contract and is able to pass the options to my custom `FieldSetFilter`.

**Comment by neomerx** [comment]
@nanawel Would be interesting to see your fork, I might steal some ideas ;)

**Comment by neomerx** [comment]
@nanawel Also, please have a look at a branch `v4-rc`. Essentially that's v3 where a Schema has an additional parameter [ContextInterface](https://github.com/neomerx/json-api/blob/8e48f9acd98fc9c5b125a695c56ed13a7a94c211/src/Contracts/Schema/ContextInterface.php#L24-L46) in `getRelationships` method
```php
    public function getRelationships($resource, ContextInterface $context): iterable
    {
        // ...
    }
```

**Update** `ContextInterface` is a simple getter. You can replace the default implementation with a custom one that optimizes implementation and has extra methods.

**Comment by nanawel** [comment]
> @nanawel Also, please have a look at a branch `v4-rc`. Essentially that's v3 where a Schema has an additional parameter [ContextInterface](https://github.com/neomerx/json-api/blob/8e48f9acd98fc9c5b125a695c56ed13a7a94c211/src/Contracts/Schema/ContextInterface.php#L24-L46) in `getRelationships` method

Ooh that's exactly how I was imagining how it could be done. 
I thougt it was missing a "context" object that could be used by the schema to know what it should return.

As I don't have enough time left on this subject I went with the "return everything even if it's slow" solution, but I should be able to get back on it soon. I'll give your v4 a try!

**Comment by neomerx** [comment]
@nanawel context added to `getAttributes` as well. Please update.

**Comment by neomerx** [comment]
@nanawel Shall I expect any feedback from you on v4?

**Comment by nanawel** [comment]
> @nanawel Shall I expect any feedback from you on v4?

Sorry, not at the moment unfortunately. But I'll give it a shot later. Thanks for your time and your advice anyway. You may close this ticket now.

**Comment by neomerx** [comment]
Released in [v4](https://github.com/neomerx/json-api/releases/tag/v4.0.0).
