### ISSUE TITLE
Catch exceptions from json_encode

### ISSUE THREAD

**Issue by efinder2** [neomerx/json-api#242]
If the json encoder in /json-api/src/Encoder/Encoder.php:413 can't parse the json properbly (e.g. Encoding problems) the function json_encode returns false. this causes in error cause of strict_types=1. This should be prevented.

**Comment by neomerx** [comment]
Is it hypothetical or you've got some real input that can't be handled?

**Comment by efinder2** [comment]
All our files are iso-8859-15 encoded. So I got an encoding exception when I try to use the api with strings with special chars like ü. Is there a way to set a base encoding?

**Comment by neomerx** [comment]
@efinder2 You can set both options and depth with methods `withEncodeOptions` and `withEncodeDepth` as described [here](https://github.com/neomerx/json-api/wiki#encode).

**Comment by efinder2** [comment]
Thank you much. I'll try it

**Comment by neomerx** [comment]
I'll keep it open for a while. I've got an idea of how to add some tips to use those methods or check if inputs (e.g. meta) can be encoded to JSON.

**Comment by neomerx** [comment]
As for strings. PHP manual [says](https://www.php.net/manual/en/function.json-encode.php#refsect1-function.json-encode-parameters) `All string data must be UTF-8 encoded.` Have a look at [predefined JSON constants](https://www.php.net/manual/en/json.constants.php) that might help you.

It seems json_encode can work with any input except resources which I guess only possible if a user adds it with `withMeta` method. I could add catching exceptions with a message like `Hey, are you sure you are not trying to encode resources? In meta section maybe?` and add the caught exception which he/she gets anyway. It looks a bit gimmicky and no real value. However, if you've got a good idea of how to add it properly please don't hesitate to share it. Also, a code sample that leads to failure is welcome.

**Comment by neomerx** [comment]
If you have any further questions please don't hesitate to ask.
