### ISSUE TITLE
Fetch a link from an existing Element

### ISSUE THREAD

**Issue by efinder2** [neomerx/json-api#246]
I'd like to get the self URL for the new created Element. According to the [spec](https://jsonapi.org/format/#crud-creating) you should send a Location-Header with the new URL. If I parse the element I get the new self::URL in JSON. How to get the URL without parsing the json and extracting the Url.

While debugging I've seen the most methods wich would be helpfull are protected in the DocumentWriter. Is there a best practice solution?

**Comment by neomerx** [comment]
> I'd like to get the self URL for the new created Element.

[This code](https://github.com/limoncello-php/framework/blob/3976bcfa4edcc358f98237ed6a51f7c303d588b6/components/Flute/src/Http/Traits/DefaultControllerMethodsTrait.php#L876-L887) might answer your question. It receives a newly created object, URL of the request to create one and a schemas.  The schemas is used to get a schema for the object and [BaseSchema::getSelfLink](https://github.com/neomerx/json-api/blob/0e45254a4574a3118e0ed663312b43aca23b89c7/src/Schema/BaseSchema.php#L53-L56) is used to create the URL.
There are multuple ways to get the schemas. Encoder [recieves them as an input](https://github.com/neomerx/json-api/blob/0e45254a4574a3118e0ed663312b43aca23b89c7/src/Encoder/Encoder.php#L94) (so when you create one you might remember it) or you can use [getter](https://github.com/neomerx/json-api/blob/0e45254a4574a3118e0ed663312b43aca23b89c7/src/Encoder/EncoderPropertiesTrait.php#L141-L144) though it's protected and you will need to do something with it.

**Comment by neomerx** [comment]
Hi, I'm closing the issue because I've got a feeling that the question has been answered. Please don't hesitate to ask any further questions.
