### ISSUE TITLE
How to encode custom array NOT LARAVEL MODEL INSTANCE

### ISSUE THREAD

**Issue by beselmonster** [neomerx/json-api#247]
![image](https://user-images.githubusercontent.com/24416981/78372781-5ea9f500-75d2-11ea-8c9d-a4393dbf0d69.png)
I just want to use my custom schema DropLineSchema to encode custom array which is array of arrays.
How to do that? Is every array in array required to be laravel model? I cant really figure out. All examples i saw had laravel models in it

**Comment by neomerx** [comment]
Hi, the library is framework agnostic and knows nothing about Laravel or any other framework.

Though it has some requirements for inputs. Simply put, you should pass either a class instance or an array of instances. The classes could be anything from `\stdClass` to Custom or Laravel or Doctrine models. The `Schemas` are the classes that know how to extract needed data from those 'models'.

**Comment by neomerx** [comment]
For you it could be
```php
class DropLine
{
    public int $id;
    public int $length;
    public int $indent;
    public string $value;
}

$arrayOfDropLines = ...;

$json = Encoder::instance([
    DropLine::class => DropLineSchema::class,
])->encodeData($arrayOfDropLines);
```

**Comment by beselmonster** [comment]
Thanks. But is there any option i can use array of arrays? When i try it, i have an error  
"assert(): assert($dataOrId instanceof SchemaIdentifierInterface) failed".

**Comment by neomerx** [comment]
@beselmonster I know nobody likes reading manuals :smile: but the spec probably do not have such thing as array of arrays therefore this lib do not have it. Array of objects might be helpful for you as shown in the example above.
