### ISSUE TITLE
Cursor pagination and attributes object

### ISSUE THREAD

**Issue by boris-glumpler** [neomerx/json-api#3]
Hey there,

looking at various packages to implement an API conform to the JSON-API spec atm and it seems yours is the most complete one so far. Looking through the readme, the only things I noticed missing were cursor-based pagination and the [attributes](http://jsonapi.org/format/#document-structure-resource-objects) top-level object to hold information about the resource. Would you be interested in PRs for these things or is this maybe already in development? Cheers!

**Comment by neomerx** [comment]
@shabushabu encode method accepts the following parameters

``` php
encode(
        $data,
        DocumentLinksInterface $links = null,
        $meta = null,
        EncodingParametersInterface $parameters = null
    )
```

Thus you can encode like this

```
$encoder->encode(
    $yourData,
    new DocumentLinks(null, '/first', '/last', '/prev', '/next')
);
```

It looks the [spec limits URLs to 'first', 'last', 'prev' and 'next'](http://jsonapi.org/format/#fetching-pagination). Is that you looking for?

'attributes' looks just added. It used to be 'type', 'id' and attributes combined. I'll update it today.

**Comment by boris-glumpler** [comment]
Alright, missed that one. Excellent! Thanks!

**Comment by neomerx** [comment]
@shabushabu Attributes representation updated in v0.1.1 The tests, documentation and sample are updated as well.

**Comment by boris-glumpler** [comment]
Great! Thanks!

**Comment by neomerx** [comment]
@shabushabu Your :star: is welcomed :wink:

**Comment by boris-glumpler** [comment]
Done ;)
