### ISSUE TITLE
How can you include certain relationships by default in the included section?

### ISSUE THREAD

**Issue by koemeet** [neomerx/json-api#31]

**Comment by neomerx** [comment]
see `getIncludePaths` description in [wiki](https://github.com/neomerx/json-api/wiki/Schemas)

**Comment by neomerx** [comment]
If you have any questions please don't hesitate to ask

**Comment by koemeet** [comment]
@neomerx Ah nice, I did not see that there are more pages in the Wiki. Thanks m8! :+1:
