### ISSUE TITLE
Relationship without a data object, but only with links. Is this possible?

### ISSUE THREAD

**Issue by koemeet** [neomerx/json-api#32]
Hi,

I am trying to have a relationship that does not include the data object and only use the links. This way my API can async load them later.

This is what I tried, but my relationship does not have any value, just `null`:

``` php
public function getRelationships($product)
{
    return [
        'translations' => [
            self::SHOW_SELF => true,
            self::SHOW_RELATED => true
        ];
}
```

Is this possible and how would I accomplish this?

**Comment by neomerx** [comment]
@steffenbrem it's is possible with `self::SHOW_DATA => false` [flag](https://github.com/neomerx/json-api/wiki/Schemas#showhide-data) however there is an issue with it. The `self::DATA` must be set to something and it must be a single resource (not array).
I have fixed array/not array issue (however it's not published yet) and investigating issue how mandatory `self::DATA` could be omitted.

**Comment by neomerx** [comment]
@steffenbrem the fix is in `develop` branch. Can you please check if it works fine for you before it's merged to `master`?

**Comment by koemeet** [comment]
@neomerx Thanks for your quick help! Yes it is indeed working, `data` is now `null` and the links are correctly displayed :+1: 

![dd](http://puu.sh/iCvQi/b658587468.png)

Maybe it is a good idea to have slack for this repo? Easier for small discussions, I noticed some things and I made some small changes myself to make it work for me.

**Comment by neomerx** [comment]
Reopen till released :wink:

**Comment by neomerx** [comment]
@steffenbrem Just in case you missed my comment.

If you add `self::SHOW_DATA => false` the `data` member should become hidden

**Comment by neomerx** [comment]
@steffenbrem sorry for asking but what is shopblender? Is it customer specific project or you do something more general?

**Comment by koemeet** [comment]
@neomerx Yep, got an error on that before somehow, but it is working now indeed. Much better without the whole `data` key. :+1: 

If you like, I created a slack team so people can talk about this repo: http://neomerxjson-api.slack.com

If you don't like it I can delete it.

**Comment by neomerx** [comment]
no probs
I use gitter btw

**Comment by koemeet** [comment]
@neomerx Yeah shopblender is a personal project, was using my own JSON-API implementation before but was very outdated. This library seems very promising :+1:

**Comment by neomerx** [comment]
I see. I was asking because I'm developing API based e-commerce and this project is kinda part of it.
