### ISSUE TITLE
PHP 5.5+ required?

### ISSUE THREAD

**Issue by danr1979** [neomerx/json-api#41]
Hi.

I am getting:

```
"FatalErrorException in Encoder.php line 145:
syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable
(T_VARIABLE) or '{' or '$'"
```

when I try to instantiate the Encoder using:

```
$encoder = Encoder::instance([
    '\My\Path\Models\MyModel' => '\My\Path\Schemas\MyModelSchema',
], new EncoderOptions(JSON_PRETTY_PRINT));
```

I am running PHP 5.4.  Is "json-api" compatible with this version or do I need to upgrade to 5.5 please?

Thanks.

**Comment by neomerx** [comment]
Yes, 5.5+ required. It uses some language constructions supported since 5.5

BTW As I remember Zend is going to drop support for 5.4 this month. So yeah, you'd better to upgrade :wink:

**Comment by danr1979** [comment]
OK np. Thank you.
