### ISSUE TITLE
Can I provide only ids of related models  to the main object?

### ISSUE THREAD

**Issue by dmagunov** [neomerx/json-api#42]
Hello,

Is were any way to provide only ids of related models to the main object (not model objects)?

**Comment by neomerx** [comment]
you can give models with ids only

**Comment by dmagunov** [comment]
Thanks for response. I have one more question: 

How can I include not related models in output json?

**Comment by neomerx** [comment]
``` php
$encoder->encode([
    $model1,
    $model2,
    $model3
]);
```

However you should remember that [spec](http://jsonapi.org/format/) requires them to have same type.

**Comment by dmagunov** [comment]
I already try this, but get the error when the models are differ.

**Comment by neomerx** [comment]
diff model types are not allowed by the spec
