### ISSUE TITLE
Nested selfSubUrl

### ISSUE THREAD

**Issue by rcrowe** [neomerx/json-api#46]
Is it possible to have a 'selfSubUrl' such as **/users/{id}/followers**.

Apologies if I missed it in the docs.

**Comment by neomerx** [comment]
Do you want {id} to be auto substituted with `$resource->id` or to see just plain string `/users/{id}/followers`?

Plain string should work. Substitution should be think through how exactly it should work.

**Comment by rcrowe** [comment]
Ideally substitution

**Comment by neomerx** [comment]
OK it looks interesting. We can discuss requirements for this enhancement online via [Gitter](https://gitter.im/neomerx/json-api)

**Comment by neomerx** [comment]
After thinking a while... :smile: 

You can override a `Schema` method that returns links

``` php
    public function getSelfSubLink($resource)
    {
        // default implementation
        return new Link($this->selfSubUrl . $this->getId($resource));
    }
```

and make url based on any `$resource` property. For example this should meet your needs

``` php
    public function getSelfSubLink($resource)
    {
        return new Link('/users/' . $this->getId($resource) . '/followers');
    }
```

**Comment by neomerx** [comment]
Please let me know if it's OK for you

**Comment by rcrowe** [comment]
That did it, thanks :)

**Comment by neomerx** [comment]
Reopen for doc update

**Comment by neomerx** [comment]
Added description to [wiki](https://github.com/neomerx/json-api/wiki/Schemas#change-self-url-format)

BTW @rcrowe IMHO you might not need URL changing like this but just a relation `followers`. As far as I understand the spec it would be more in line with it.
