### ISSUE TITLE
Lazy load relationship data

### ISSUE THREAD

**Issue by rcrowe** [neomerx/json-api#48]
I have the following code:

``` php
    public function getRelationships($user)
    {
        return [
            'followers' => [
                self::SHOW_DATA    => false,
                self::DATA         => function () use ($user) {
                    return $user->followers;
                },
                self::SHOW_RELATED => true,
            ]
        ];
    }
```

It would be nice if that closure wasn't evaluated until needed. In my case when `include=followers` in which case you would then call and render.

It seems like I have to potentially run multiple SQL statements even if the data isn't returned in the JSON.

**Comment by neomerx** [comment]
@rcrowe I've added lazy loading to branch `issue48` however spec doesn't allow it work as you expected. By default all fields (attributes and relationships) are shown and you can keep visible some of them.
With field sets you can specify which fields (no nest naming) should be shown for each type and encoder will evaluate data only for those.
Look forward for your feedback.

**Comment by neomerx** [comment]
@rcrowe `SHOW_DATA` cannot be used for managing visibility this way. It's intended to be used for fine tuning the final view. For example, you want to produce the following json

``` json
{
    "data" : {
        "type"  : "posts",
        "id"    : "1",
        "attributes" : {
            "title" : "Title",
            "body"  : "Body"
        },
        "relationships" : {
            "author" : {
                "links" : { "related" : "http://example.com/posts/1/author" }
            },
            "comments" : {
                "links" : { "foo" : "http://example.com/posts/1/another/link" }
            }
        },
        "links" : {
            "self" : "http://example.com/posts/1"
        }
    }
}
```

Both relationships `author` and `comments` have `data` hidden and only `links` shown. Despite this `data` are needed for selecting proper `Schema` and link creation (note link might include fields such as `id` and others). So you might want to include limited data set and then hide it.

That's how it works now. However I find your idea with `SHOW_DATA` interesting and will think if it could be implemented.

**Comment by rcrowe** [comment]
My use case is with `includes, which the API I'm building makes heavy use of.

As far as I can tell, when passing the includes to `EncodingParameters` it make's use of the the data set on the relationships.

If I have 10 relationships with data, it seems like I have to run all these queries even though the data may never be returned to the client.

**Comment by neomerx** [comment]
@rcrowe I was actually able to refactor parser and now it skips data evaluation for hidden relationships! :smile: 

Check it out in branch `issue48`

**Comment by rcrowe** [comment]
Taking a look now :smile:

**Comment by rcrowe** [comment]
https://github.com/neomerx/json-api/blob/issue48/src/Encoder/Parser/ParserManager.php#L82

`array_has` is undefined.

**Comment by neomerx** [comment]
Fixed

**Comment by rcrowe** [comment]
So it seems while the parser does now skip data here:

``` php
self::SHOW_DATA => false,
self::DATA      => function () use ($user) {
    return $user->followers;
}
```

`includes` are now being skipped.

**Comment by neomerx** [comment]
Can you please provide an example?
Can we switch to https://gitter.im/neomerx/json-api ? It has better notification system.

**Comment by rcrowe** [comment]
Sure, on my way :+1:

**Comment by rcrowe** [comment]
As discussed, happy to close as the `issue48` branch fixes the lazy loading
