### ISSUE TITLE
Make `SHOW_DATA=false` able to be overridden in relationships with`include` parameters

### ISSUE THREAD

**Issue by neomerx** [neomerx/json-api#49]
Relationships could be hidden by default with only meta or links shown by default. If `include` parameter has the path it should override`SHOW_DATA` to `true` and render the data.

Related to #48

**Comment by neomerx** [comment]
@rcrowe check this out

**Comment by rcrowe** [comment]
That sounds bad ass :fire: - looking forward to testing

**Comment by neomerx** [comment]
@rcrowe plz check out early version in `issue49`. It's not polished, cleaned and a bit hacky at the moment but works at some scenarios.

**Comment by neomerx** [comment]
@rcrowe I've added this custom logic via extension and merged to `develop` branch. You need to extend parser to change logic for your code. Have a look at [full sample code + test](https://github.com/neomerx/json-api/tree/develop/tests/Extensions/Issue49).

**Comment by neomerx** [comment]
@rcrowe I haven't heard from you for some time, improved the code a bit and released it as [v0.5.6](https://github.com/neomerx/json-api/releases/tag/v0.5.6). If you have any further questions please don't hesitate to ask.
