### ISSUE TITLE
Add chain methods for parameters in Encoder

### ISSUE THREAD

**Issue by neomerx** [neomerx/json-api#59]
Related to #55

**Comment by neomerx** [comment]
@Xobb Hi, I have noticed you might have an interest in a JSON-API.

You could be interested in [PHP json-api](https://github.com/neomerx/json-api) which implements the latest spec v1.0 (aka **RC4**) and works with Ember and Laravel.

**Comment by neomerx** [comment]
@mgustafsson1 Hi, I have noticed you might have an interest in a JSON-API.

You could be interested in [PHP json-api](https://github.com/neomerx/json-api) which implements the latest spec v1.0 (aka **RC4**) and works with Laravel such frameworks as Ember out of the box.

**Comment by neomerx** [comment]
@zhiephie Hi, I have noticed you might have an interest in a JSON-API.

You could be interested in [PHP json-api](https://github.com/neomerx/json-api) which implements the latest spec v1.0 (aka **RC4**) and works with Ember and Laravel. I've got a sample Laravel app that already has [JSON-API support integrated](https://github.com/neomerx/limoncello-collins) and working on adding Basic/Bearer/JWT Auth and CORS support to it.

If you have any questions please don't hesitate to ask on [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/neomerx/json-api)

**Comment by zhiephie** [comment]
Thanks @neomerx

**Comment by neomerx** [comment]
@zhiephie I finished adding JWT/Bearer/Basic Auth + CORS yesterday. Feel free to ask any question :wink:
