### ISSUE TITLE
Semver

### ISSUE THREAD

**Issue by boris-glumpler** [neomerx/json-api#6]
To follow semver, shouldn't the version numbers be more like `0.2.0`, so that you can do something like `~0.2.0` in composer.json. Not that it matters much as long as the version isn't 1.0.

I'm guessing you're planning to tag v1.0.0 when the spec becomes stable?

**Comment by neomerx** [comment]
Yes, probably you are right. All semver examples are with 'patch' version and it's not mentioned that it could be omitted. From the next version I'll be adding the 'patch' for all releases.
Yes, you are right I think JSON API should become stable. They still are doing some tweaks like 'attributes' issue you've found today.

**Comment by boris-glumpler** [comment]
Not sure neither if it can be omitted. I've only ever seen it with patch. As I said, not really that important yet, just thought I'd mention it.

**Comment by neomerx** [comment]
released 0.2.1
