### ISSUE TITLE
Easier encoding for paging links

### ISSUE THREAD

**Issue by neomerx** [neomerx/json-api#61]
##### That's an issue for discussion how to make pagination links generation easier.

As JSON-API spec [says](http://jsonapi.org/format/#fetching-pagination) it is agnostic about the pagination strategy as there are at least a few possibilities e.g. page-based, offset-based, and cursor-based. For this reason pagination strategy is not detailed in the spec.

Currently paging links could be generated like this

``` php
$links = [
    Link::FIRST => new Link('/authors?page=1'),
    Link::LAST  => new Link('/authors?page=4'),
    Link::NEXT  => new Link('/authors?page=6'),
    Link::LAST  => new Link('/authors?page=9'),
];
$encoder->withLinks($links)->encodeData($authors);
```

While this approach is almost fine it would've better if `Encoder` looked into `$authors` and took sub-URL part `/authors` from `AuthorSchema`.

The question is what interface such a method could have to be flexible and easy to use? There are a few thinks that should be in mind: URLs might be relative as in the sample above or absolute `http://example.com/api/authors?...`, links might [have meta information](http://jsonapi.org/format/#document-links) and different paging strategies are possible.

One of the possible approach

``` php
$encoder
    ->withPagingLinks([Link::FIRST, Link::LAST, ...], $pageLinksGenerator)
    ->encodeData(...);
```

Where first parameter is a list of desired links (all possible values are defined by the spec) and `$pageLinksGenerator` is an instance of a class which implements

``` php
interface PageLinksGeneratorInterface
{
    public function getLink(string $linkKey, string $schemaSubUrl);
}
```

So `PageLinksGeneratorInterface` implementation e.g. `PageBasedLinksGenerator` will do it for particular strategy and user can chose which one to use.

**Comment by lindyhopchris** [comment]
@neomerx 

Think the `withPagingLinks` method might work. How would you include other links (i.e. links that aren't paging related) in the same links object in the document that is encoded? E.g. if the document links object was to include `self` as a link as well as the paging links?

The other thing to bear in mind about paging links is they are not only limited to the top level (document) scope. For the spec:

>  To paginate the primary data, supply pagination links in the top-level links object. To paginate an included collection returned in a compound document, supply pagination links in the corresponding links object.

I think an example of the latter is providing pagination links in the links object on a has-many relationship. Would your paging links generator approach work for that too?

**Comment by neomerx** [comment]
> How would you include other links

You can combine those methods. If a link key is used more than once the last `Link` value will be used

``` php
$encoder
    ->withPagingLinks([Link::FIRST, Link::FIRST, ...], $pageLinksGenerator)
    ->withLinks([...])
    ->encodeData(...);
```

> The other thing to bear in mind about paging links is they are not only limited to the top level

Very good point. Similar kind of helper method is needed to be accessible from `Schema` (from method `getRelationships` in particular). I can't figure out syntax of that method however it should be similar to `withPagingLinks`. These links will be placed in `links` section of the relationship.

**Comment by lindyhopchris** [comment]
> You can combine those methods

Ah yep, had missed that. Works nicely.

> I can't figure out syntax of that method however it should be similar to `withPagingLinks`

Definitely makes sense to try to keep the method signatures as close as possible.

**Comment by neomerx** [comment]
That's [another piece of paging puzzle](http://guides.emberjs.com/v1.13.0/models/handling-metadata/)

**Comment by lindyhopchris** [comment]
@neomerx what's the complication with that? I'd take that doc page with a pinch of salt as the example server response isn't JSON API, plus Ember Data v2.0 will be built to default to the JSON API spec.

**Comment by neomerx** [comment]
Ember drives me crazy :smile: I'be been spending past two days with Ember documentation, samples and videos. I just want to do a simple form with fields for attributes and combo/drop-down-list/select for one of the relationships with all data taken from backend.

Looking for paging was't my priority but that link was the only I found. And yes you right it's not relevant :smile:

**Comment by neomerx** [comment]
Let's say we have data which were filtered and sorted before it's passed to `Encoder`. How can we look at those data and say which filtering and sorting parameters were applied? We can't. Thus it's a fundamentally wrong idea to generate URLs based on provided data. The party which sends data to encoder should compose proper URLs. The lib currently provides all the means for that.

I'm closing this open question.
