### ISSUE TITLE
Adding multiple errors

### ISSUE THREAD

**Issue by yoanisgil** [neomerx/json-api#63]
According to the wiki it's possible to do something like:

```
$error = new Error(
    'some-id',
    new Link('about-link'),
    'some-status',
    'some-code',
    'some-title',
    'some-detail',
    ['source' => 'data'],
    ['some'   => 'meta']
);

Encoder::instance([])->encodeError($error);
```

but it does not seem possible to add multiple errors. Or is it? If so what would be the way to do so?

My use case is the following:
- A user sends a domain/ip address as part of an HTTP request (JSON encoded in the request body). I want to validate both parameters before proceeding further with the request. I want to return all possible errors (i.e, invalid domain and invalid ip address, etc). 

Is this possible?

**Comment by neomerx** [comment]
Yes sure, you can add multiple errors with method [encodeErrors](https://github.com/neomerx/json-api/wiki#encode)

``` php
    /**
     * Encode errors as JSON API string.
     *
     * @param ErrorInterface[] $errors
     *
     * @return string
     */
    public function encodeErrors($errors);
```

**Comment by yoanisgil** [comment]
Oops! I missed that. Thanks a lot! I think you can close the issue. I will give it a try tomorrow at work ;)

**Comment by neomerx** [comment]
No probs. Feel free to ask.

**Comment by neomerx** [comment]
@yoanisgil  Your support :star: will be much appreciated :wink:
