### ISSUE TITLE
Error Details Array?

### ISSUE THREAD

**Issue by Olofguard** [neomerx/json-api#66]
I'm new to the JSON Api Spec, and this may be more of an opinion/personal preference; However, if you were to encounter something like validation errors in your api, you could handle this in two ways. 

You could return an array of errors with each index being it's own validation/field error. Like so:

```
{
  "errors": [
    {
      "links": {
        "about": ""
      },
      "status": "Unprocessable Entity",
      "code": "422",
      "title": "Validation Error",
      "detail": "city: The city field is required.",
      "source": [],
      "meta": []
    },
    {
      "links": {
        "about": ""
      },
      "status": "Unprocessable Entity",
      "code": "422",
      "title": "Validation Error",
      "detail": "zip: The zip field is required.",
      "source": [],
      "meta": []
    }
  ]
}
```

This is valid and with my limited experience this may be the standard, but I would prefer to return one 
error, a validation error. I would put each violating field and it's validation error message in a json array in the details of the response. Like so: 

```
{
  "errors": [
    {
      "links": {
        "about": "http://api.styleanddelight.dev"
      },
      "status": "422",
      "code": "",
      "title": "Validation Error",
      "detail": {
        "city": "The city field is required.",
        "zip": "The zip field is required."
      },
      "source": [],
      "meta": []
    }
  ]
}
```

This is not  currently possible with the way the `Neomerx\JsonApi\Document\Error` object is constructed. I was able to extend the `Error` object and overwrite the `getDetail` method to return an array. Otherwise I would have to `json_encode()` the errors in order to pass them in as a string to the Error instantiation. This, however, results in a doubly encoded json array for the details prop.

It would be nice if I could pass an array or string in for details on the Error Object.

**Comment by neomerx** [comment]
Before [breaking the rules](http://jsonapi.org/format/#error-objects) a friendly reminder that outside world [might have expectations about API behavior](http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_using-json-api-error-object-format).

You might noticed the package is built around interfaces and `Error` is not an exception (so you can either create a new class or extend an existing one). I got you tried to inherit `Error` class but didn't get what kind of problem you had. I'd try to inherit `Error` class **do not call its constructor** as it's the [place where data are checked](https://github.com/neomerx/json-api/blob/master/src/Document/Error.php#L93) but set the properties in your new constructor (copy-paste basically). Then try to encode. I expect it should work.

UPD I personally think it's a bad idea. You might only save up some bytes but they will be eliminated by HTTP server gzip anyway (if worth doing it).

**Comment by Olofguard** [comment]
:+1:  Thanks. The link to the usage of a json api error object was insightful.
