### ISSUE TITLE
Parameters Checking vs Header Checking

### ISSUE THREAD

**Issue by lindyhopchris** [neomerx/json-api#68]
Hi!

I'd like to suggest adding a `HeaderCheckerInterface` and then splitting `RestrictiveParameterChecker` into two - i.e. so that you can have one object that checks headers, and the other that checks parameters.

The reason for doing it is because in frameworks that use middleware (e.g. Laravel), the headers should be checked in middleware as the `Accept` and `ContentType` headers should be consistent across controllers. Knowledge of what parameters are acceptable can then be checked by the controller.

In an event based framework (e.g. Zend 2) the headers would be checked on dispatch of the event, before the event lands in a controller.

I'm happy to submit a pull request if you agree on splitting them.

**Comment by neomerx** [comment]
I have no objections. It's fine if you post early (not ready) version for discussion.

**Comment by neomerx** [comment]
merged to master
