### ISSUE TITLE
Add support for polymorphic data in one relationship

### ISSUE THREAD

**Issue by neomerx** [neomerx/json-api#74]
Encoder should be able to encode relationship (array/collection) where resources have different types.

**Comment by neomerx** [comment]
branch `feature/issue74` created

**Comment by neomerx** [comment]
@lindyhopchris @ronaldo-systemar I think polymorphic is ready. Can you please check out the latest version from `feature/issue74` branch and give your feedback?

**Comment by lindyhopchris** [comment]
@neomerx sorry, just seen this. will take a look at work tomorrow morning and try it out with the stuff we've got there.

**Comment by lindyhopchris** [comment]
@neomerx looks great :-)

**Comment by ronaldo-systemar** [comment]
Merged models like this and doesn't work:

```
    public function mergeModels($models = [], $table)
    {
        $merge = [];

        foreach ($models as $model) {
            $merge = array_merge($merge, $this->morphedByMany($model, $table)->get()->all());
        }

        return $merge;
    }
```
