### ISSUE TITLE
Framework agnostic JSON-API client

### ISSUE THREAD

**Issue by yoanisgil** [neomerx/json-api#77]
Hi @neomerx ,

I was wondering if there is already a framework agnostic client implementation which nicely integrates with the JSON API implementation provided by this project? I am considering using this one: https://github.com/Art4/json-api-client but wanted to check with you just in case you might have a better suggestion.

**Comment by neomerx** [comment]
@yoanisgil something similar @lindyhopchris is doing in his project https://github.com/cloudcreativity/json-api

**Comment by lindyhopchris** [comment]
@yoanisgil 

my project is similar in that it provides ways of validating JSON API input. I'm using it to validate request content and send JSON API error objects back to the client telling them what's wrong with the content (which is really important for public facing APIs, plus helps when developing client applications). It also parses the input to a standard object interface to help with handling the content.

At the moment it could validate the response received from a server, though it'd need some extra validators e.g. for validating collection responses.

I hadn't seen the other one that you've provided a link to but it looks useful.

**Comment by yoanisgil** [comment]
@lindyhopchris I have a collection of web services available via a RESTful API. These services were designed to be small and composable so a good degree of reusability could be achieved througout the life cycle of a few applications. These applications will be consuming the afore mentioned services and, given that they try to stick to the JSON API specification, I 'm looking for client side implementation. I'm going to give it a try to your project and get back to you.

@neomerx thanks for the reference ;)
