### ISSUE TITLE
Support resource identity as a pair of type and id (array)

### ISSUE THREAD

**Issue by neomerx** [neomerx/json-api#81]
An idea from @lindyhopchris to support relationships not only as classes with empty attributes but as a pair of type and identity as well

``` php
public function getRelationships($comment, $includedRelationships = [])
{
    return [
        'author' => [
            static::DATA => isset($includedRelationships['author']) ? 
                $comment->getAuthor() :
                [AuthorSchema::class, $comment->author_id],
        ],
    ];
}
```

**Comment by neomerx** [comment]
@lindyhopchris btw `$includedRelationships` will have relationships not only as values but as keys as well. I guess isset/has_key should work faster.

**Comment by neomerx** [comment]
I've made a small patch not related to this issue in this branch. It improves scrutinizer's ranking (9.42▲+0.06) and synthetic speed test for about 5-7% (I got 12% once).

**Comment by neomerx** [comment]
@lindyhopchris An array is probably not gonna work. It can be confused with an array of ordinary resources. Probably something like `ResourceIdentifierInterface` is a better candidate. Which btw might have an embedded schema.

**Comment by neomerx** [comment]
I've played a little with code for this enhancement and came up to the following idea.
Add `createIdentity` method to `Schema` so it could be used in relationships as

``` php
public function getRelationships($comment, $includedRelationships = [])
{
    return [
        'author' => [
            static::DATA => isset($includedRelationships['author']) ? 
                $comment->getAuthor() : $this->createIdentity(Author::class, $comment->author_id)
        ],
    ];
}
```

The implementation solution will include
- a new `DataIdentity` class for storing model's class and id.
- changes to `SchemaProvider` so it can separate handling of `DataIdentity` from other classes. It will take model's class from `DataIdentity`, find a `Schema` for that model class and create a special schema wrapper `DataIdentitySchema`
- `DataIdentitySchema` will be built-in `Schema` that passes all requests to underlying `Schema` apart those that has `$resource` as input parameter (e.g. `getAttributes`, `getRelationsips`, `getId`). It will return id from `DataIdentity` in `getId` and rise exception for others as it has no real resource data.

**Comment by neomerx** [comment]
Also there is a simpler alternative. For cases when a model could not be created with just `id` and **any** other attributes (I'm still in doubts why such model could not be created) a simple classes could be created for such models with theirs `Schemas`. For example

``` php
class AuthorIdentity
{
    public id;
}
```

and its `Schema`

``` php
class AuthorIdentitySchema extends DataIdentitySchemaProvider
{
    protected $resourceType = AuthorSchema::TYPE;
    protected $selfSubUrl   = AuthorSchema::SUB_URL;

    public function getId($authorIdentity)
    {
        return $authorIdentity->id;
    }
}
```

`DataIdentitySchemaProvider` will just add empty implementation for `getAttributes`

As I see this issue a rare case and it has a simple solution I tend to think we should not make the implementation more complex and process with this issue. I propose close the issue.

**Comment by lindyhopchris** [comment]
I like the `createIdentity` solution. When you say you propose closing the issue, do you mean with the `createIdentity` as added to the code base?

If so, does `createIdentity` work if the second argument is `null`? That would be nice as it would make things simpler in the schema provider as you wouldn't have to check whether the e.g. `author_id` was `null` or not before calling `createIdentity`.

**Comment by neomerx** [comment]
I did some code for the issue however when I understood there were a simpler workaround for the issue I removed the code. Adding `createIdentity` as I described adds 'special treatment' for `DataIdentity` to core components and 'smells' for this reason. I liked how elegant it could be in code however same effect could be achieved with adding identity schemes. For example

``` php
public function getRelationships($comment, $includedRelationships = [])
{
    return [
        'author' => [
            static::DATA => isset($includedRelationships['author']) ? 
                $comment->getAuthor() : new AuthorIdentity($comment->author_id)
        ],
    ];
}
```

`AuthorIdentity` and `AuthorIdentitySchema` had trivial implementation as above. Moreover `Schema` could be passed to `Encoder` as a `Closure` and I think it might be universal for all such schemes.

**Comment by neomerx** [comment]
something like

``` php
$encoder = Encoder::instance([
    Author::class  => AuthorSchema::class,
    AuthorIdentity::class => $this->createIdentitySchemaClosure(AuthorSchema::class),
]);

class DataIdentitySchema extends SchemaProvider
{
    protected $resourceType = AuthorSchema::TYPE;
    protected $selfSubUrl   = AuthorSchema::SUB_URL;

    public function __construct($type, $subUrl)
    {
        $this->resourceType = $type;
        $this->selfSubUrl   = $subUrl;
    }

    public function getId(DataIdentityInterface $dataIdentity)
    {
        return $authorIdentity->id;
    }
}
```

Thus it will require to only add 3 lines identity classes.

**Comment by lindyhopchris** [comment]
I don't think this is a simple work around at all; particular as I have an application with 60+ models in it.  That's not a trivial implementation to add 60+ identity classes and 60+ extra schemas - classes that only exist because I need to encoder to encode an id that the schema already has access to!

**Comment by lindyhopchris** [comment]
I don't think the example is as easy as you think it is. It'd actually be this:

``` php
public function getRelationships($comment, $includedRelationships = [])
{
    return [
        'author' => [
            static::DATA => isset($includedRelationships['author']) ? 
                $comment->getAuthor() : (!empty($comment->author_id)) ? new AuthorIdentity($comment->author_id) : null
        ],
    ];
}
```

I feel like being able to just return a Schema class and an id (that can be a string/int or null if the relationships is empty) is something that should be on the public api of the schema provider. It feels like core functionality, rather than something that you have to implement a load of custom classes for - which just feels hacky.

**Comment by neomerx** [comment]
Good point with nullable value though.

I understand you like it to be core functionality (for the same reason I liked it in the first place). However implementation I found is hacky and I feel it make difficult to enhance the project in the future.

I would take your original idea and your point about nullable values and would try implement the following logic 'if you can not create a model with just an id you can create an identity and declare its Schema in a form of Closure'. Thus it will require just adding `XyzIdentity` classes for such models and 1 line per model to schema mappings on Encoder creation.

**Comment by neomerx** [comment]
The package could be extended for usage of simple lightweight models and schemes. An example of that was added to [test suite](https://github.com/neomerx/json-api/tree/develop/tests/Extensions/Issue81)
