### ISSUE TITLE
How to make asserts better

### ISSUE THREAD

**Issue by aedart** [neomerx/json-api#83]
At the moment, I am working on implementing a base package, for dealing with Json Api, which uses your package. It works great... But its really difficult to know why some of my tests fail - when you have several conditions, in a single assert!

(_Happened after upgrading to version 0.6.0, in which you changed the some of the public API of your interfaces._)

Example: I' getting the following failure message, in one of my tests;

```
 [PHPUnit_Framework_Exception] assert(): Assertion "is_string($resourceType) && empty($resourceType) === false &&isset($this->providerMapping[$resourceType]) === false &&((is_string($schema) && empty($schema) === false) || $schema instanceof Closure)" failed
```

From the `\Neomerx\JsonApi\Schema\Container::register()`.

This is really difficult to debug, for anyone. You have to go throw every single line and try to guess what's wrong - or in worst case, you have to create tests for every single condition, just to figure out that, e.g. your mocked schema is expected to return a resource type - or whatever might be wrong.

**Suggested solution**
You should split those asserts into several smaller asserts or perhaps methods.
Ideally, you would throw some kind of custom exception, for each condition that is is not satisfied, and thereby letting the developers know exactly what is wrong, instead of "a bunch of conditions are not satisfied"...

**Comment by lindyhopchris** [comment]
:+1: 

I've had problems debugging for exactly the same reason. Personally I prefer throwing exceptions but multiple asserts would be nice.

@neomerx I'm happy to help out with this if you wanted. Just allocate me some namespaces to work through and I'll split up the asserts.

**Comment by neomerx** [comment]
@aedart The problem with asserts they are slow. Even if asserts are turned off in PHP config they slow down code and if they are on they affect performance significantly. So more asserts is hardly an option.

HHVM handles asserts **much** better but it's not mainstream, isn't it?

Asserts turned **on**

```
$ time php -d assert.active=1 sample.php -t=10000
Neomerx JSON API performance test (10000 iterations)...

real    0m5.159s
user    0m5.136s
sys     0m0.020s
```

Asserts turned **off**

```
$ time php -d assert.active=0 sample.php -t=10000
Neomerx JSON API performance test (10000 iterations)...

real    0m2.785s
user    0m2.763s
sys     0m0.020s
```

Back to possible solution. If I had that problem I would place a breakpoint and see the value or used old-school 'dump and die' technique. What can make it easier is adding a second parameter to assert with explanation what's wrong with its first expression. I've added such explanations to places I expected people would bump into most frequently and if more asserts need it could be a first step.

In code the mentioned assert looks readable IMO

``` php
assert(
    'is_string($resourceType) && empty($resourceType) === false &&'.
    'isset($this->providerMapping[$resourceType]) === false &&'.
    '((is_string($schema) && empty($schema) === false) || $schema instanceof '. Closure::class . ')'
);
```

first line '$resourceType must be non-empty string'
second line '$resourceType must not be used in mapping more than once'
third line '$schema must be non-empty string or Closure'

So the second parameter in assert could be 'Resource type should not be used more than once to register a schema. Resource type and schema must be non-empty strings. Schema could be a Closure as well.'

I have nothing against exceptions and use them very widely however for issues specific for development time I tend to use asserts.

**Comment by lindyhopchris** [comment]
@neomerx 

The problem with the assert string message is that you don't know which variable has caused the assert to fail and then you have to start digging into it. A single assert per variable or an exception per variable tells you exactly which variable is wrong. Which is why I normally do that even if it takes slightly longer to write.

Do you know how speed is affected if exceptions were used instead?

**Comment by neomerx** [comment]
@lindyhopchris No I don't. I expect it to exactly equal to `if` execution time.

**Comment by neomerx** [comment]
@lindyhopchris in code `assert` is used 33 times. So it will probably require up to a hundred of checks with if + exceptions. If you think it worth doing it we can start it after #81

**Comment by aedart** [comment]
@lindyhopchris I agree with your statement, regarding multiple asserts, rather than a single. It would be much easier to debug.

However, personally, I do prefer to create my own custom assertXYZ methods, that throw a cusatom exception. Depending on the context, a failure in the application might be cause by a bad request, rather than the developer, and thus a different exception-handling strategy might be taken in use, during runtime.

As for the performance, @neomerx , In my point of view, the `assert()` needs to parse / eval the string into native PHP code, before actually executing it, and then trigger the actual assertion; if some condition is true or not. This seems, at least for me, to require a lot more, than a simple if-condition. Sure, you would require lots of such conditions, but I do think that it will be slower, since it is native code, rather than a string that has to be parsed and executed.

Nevertheless, if its a question of simplicity, perhaps creating your own custom validators, with, e.g. a few methods, could resolve this very nicely. Your code should theoretically be much more testable and well as reusable; if the same validation / assertion is required across multiple instances, a single validator can handle such responsibility.

Example;

``` php
/**
 * Class MyApiException
 *
 * Base exception for all API related exceptions
 */
class MyApiException extends \RuntimeException{}

/**
 * Interface Validator
 */
interface Validator {

    /**
     * Check if this validator's condition is true
     *
     * @return bool True if valid, false if not
     */
    public function isValid();

    /**
     * Get a class path to this validator's exception,
     * which must be thrown
     *
     * @return string Class path to this validator's assertion-exception
     */
    public function getAssertionExceptionClass();

    /**
     * Assert this validator's condition
     *
     * @return void
     *
     * @throws MyApiException
     */
    public function assert();
}

/**
 * Class Base-Validator
 *
 * Abstraction that all validators can / should use
 */
abstract class BaseValidator implements Validator{

    protected $exceptionClass = MyApiException::class;

    public function getAssertionExceptionClass(){
        return $this->exceptionClass;
    }

    public function assert() {
        if(!$this->isValid()){
            $exceptionClass = $this->getAssertionExceptionClass();
            throw new $exceptionClass();
        }
    }
}

class ResourceTypeValidator extends BaseValidator{

    protected $schema;

    public function __construct($schema){
        $this->schema = $schema;
    }

    public function isValid() {
        if(!empty($this->schema->getResourceType())){
            return true;
        }
        return false;
    }
}

/**
 * Use-case, where ever it is needed
 */
(new ResourceTypeValidator($someRandomSchema))->assert();
```

I have obviously not taken the concrete scenario into account, and the above stated example would require adaptation, for this package's needs. You could also create the validators with a static assert-method, but it really depends on your taste. And yes - this will require a lot more work, unfortunately. But as already mentioned, I think that it could potentially increase your overall code quality.

**Comment by neomerx** [comment]
I think replacing asserts that check input parameters with `if + exception` might work out. There are also some asserts that check internal logic and assumptions useful while refactoring. The latter ones will not trigger errors for casual user unless the code is under heavy refactoring. Such asserts might have more than one condition IMO. As we've made some big changes recently reviewing them will be beneficial.

**Comment by neomerx** [comment]
I've replaced all asserts with `if + exceptions`. Profiler says it reduced time for (-36%) and Memory usage (-27%). I've got some moderate improvement in speed in synthetic tests as well.

**Comment by aedart** [comment]
That's great - thanks. Looking forward to the next release.
