### ISSUE TITLE
Use PSR-7

### ISSUE THREAD

**Issue by SamMousa** [neomerx/json-api#86]
The parameter parser currently uses a custom "CurrentRequestInterface", instead it should use PSR-7 ServerRequestInterface.

http://www.php-fig.org/psr/psr-7/

**Comment by neomerx** [comment]
Added in a form of supporting any such interfaces. For example if `$resuest` is PSR-7 `ServerRequestInterface`it could be used with `ParametersParserInterface` in the following way

``` php
$request = ...;
$adapter = new RequestClosureAdapter(
    function () use ($request) {
        return $request->getBody();
    },
    function () use ($request) {
        return $request->getQueryParams();
    },
    function ($name) use ($request) {
        return $request->getHeader($name);
    }
);

$thrower = ...;
$parser  = ...;
$result  = $parser->parse($adapter, $thrower);
...
```

[full testing source code](https://github.com/neomerx/json-api/blob/develop/tests/Extensions/Issue86/IssueTest.php)
