### ISSUE TITLE
Neomerx\JsonApi\Responses\Responses removes middleware headers

### ISSUE THREAD

**Issue by nickelozz** [neomerx/json-api#88]
Hi!

I'm using `tymon/jwt-auth` to implement JWT along with this package and it seems like when returning a collection|item response created by (as far as I've been able to track down) the method createResponse() in the `Neomerx\JsonApi\Responses\Responses` class, tymon's jwt.refresh after middleware Authorization JWT token header gets removed from the response.

Is there currently any way to prevent what seems to be an overwrite of the headers in the response?

Thank you

**Comment by nickelozz** [comment]
Hey again!

After some more testing I found out I was wrong by a long shot, sorry :disappointed: 

Turns out there's no overwrite of the response headers, instead the issue was being caused by a malformed middleware. I apologize for the confusion.

**Comment by lindyhopchris** [comment]
@nickelozz No worries, glad you got it sorted :-)
