### ISSUE TITLE
Make it easier to declare "simple" relationships

### ISSUE THREAD

**Issue by bobbysciacchitano** [neomerx/json-api#90]
Hi,

I'm using json-api with Lumen and was wondering if there was a way of being able to declare a relationship by its ID without having to load a coerce it into a model?

For example (pseudo)

``` php
/**
 * @inheritdoc
 */
public function getRelationships($resource, array $includeRelationships = [])
{
    return [
        'organisation' => [ self::SIMPLE => [ 'class' => Organisation::class, 'id' => $resource->organisation_id ] ],
    ];
}
```

**Comment by neomerx** [comment]
Yes, you can avoid data requests for relationships. Have a look at [this wiki page](https://github.com/neomerx/json-api/wiki/Schemas) especially the part about `$includeRelationships` parameter. A usage sample could be found [here](https://github.com/neomerx/json-api/tree/develop/tests/Extensions/Issue81).

One more [example](https://github.com/neomerx/limoncello-collins/blob/master/app/Schemas/CommentSchema.php#L49-L61)

**Comment by neomerx** [comment]
Don't hesitate to ask if you have any further questions
