### ISSUE TITLE
Inclusion of parent in Parent/Child relationship causes an error

### ISSUE THREAD

**Issue by geniuscd** [neomerx/json-api#91]
Hey,
I have a 'Parent' named column inside the 'Category' table in my database. 'Parent' is foreign key to the same table ofcourse. ( pointing to 'ID' ).
I'm trying to create a restful server, that follows jsonapi.org guidelines.
and of course im implementing it using this superb library!

i came across this issue where i can fetch one resource without any problem, the parent is included inside the 'inlcuded' attribute. but when im fetching an array of resources i got the following error message

> PHP Catchable fatal error:  Argument 1 passed to Neomerx\JsonApi\Document\Presenters\ElementPresenter::setRelationshipTo() must be of the type array, null given, called in /vendor/neomerx/json-api/src/Document/Document.php on line 253 and defined in /vendor/neomerx/json-api/src/Document/Presenters/ElementPresenter.php on line 54

My table Category Structure ( example )

| ID | Description | Parent |
| --- | --- | --- |
| 1 | Main | null |
| 2 | Laptop | 1 |
| 3 | PC | 1 |
| 4 | Screen | 2 |
| 5 | Big | 4 |
| 6 | small | 4 |

my Category Model contains a property called 'Parent' of type _ModelCategory_
_CategoryModel_ gets filled using a _ModelHydrator_ that gets its data from the _ModelMapper_ ( provider)

weird enough! when I'm fetching only one resource , its working normally. But when i try to fetch a collection, an error is thrown.
I tried to change the Parent Model, swap it with another model , it worked...
- maybe its an error that occurs only when including same model in the structure?
- any clue? is anyone having this issue?

ps: i'm not allowed at the moment to upload the files that i'm working on, due to restrictions :/ but i will, after creating a sample that reproduce this error.

**Comment by neomerx** [comment]
@geniuscd An example that reproduces this issue would be much appreciated.

Probably your `Schema` for `Category` is the key to the issue. Can you post it please?

**Comment by neomerx** [comment]
added test that reproduces the issue https://github.com/neomerx/json-api/tree/feature/issue91/tests/Extensions/Issue91

**Comment by neomerx** [comment]
Fixed. Test has been moved to `develop` branch https://github.com/neomerx/json-api/tree/develop/tests/Extensions/Issue91

**Comment by geniuscd** [comment]
wow, that was fast! I didnt even build a sample code! thanks for the swift reply.
what I did is downloaded the src folder from the develop branch, and replaced it in my vendor/neomerx folder, and just fetch the resources.
I can confirm that now it displays the data as expected. but the inlcuded attribute is excluded :P, that means when I fetch a single resource, its working.. but again when i fetch a collection, the included attribute is missing.
should we create an new issue for it? or just continue working on #91?

**Comment by neomerx** [comment]
@geniuscd If a resource is within main and included it will be removed from `included`. 
`included` is excluded from output if it is empty.

**Comment by geniuscd** [comment]
@neomerx could you please share a link where jsonapi v1.0 states what you mentioned?

**Comment by neomerx** [comment]
@geniuscd Nope, I propose you to find in the spec where it is prohibited :smile: Logically it doesn't make any sense to duplicate a resource in `included` if it is already on main list. As for empty `included` why do you think this empty section should be in output? Does it make any difference?

**Comment by philbates35** [comment]
I think the relevant bit is here: http://jsonapi.org/format/1.0/#document-compound-documents

> A compound document **MUST NOT** include more than one resource object for each type and id pair.

So each pair of type and id can only appear once in the document - either in `included` or somewhere in `data`, but not in both.

**Comment by geniuscd** [comment]
@neomerx totally right for the empty `included` attribute. +1 for that, I already though of it, it useless to include it.
@lindyhopchris thank you. I missed the `compound document` :)
well i think the issue is fixed .. happy to collaborate :)

**Comment by neomerx** [comment]
will be closed when merged to master
