### ISSUE TITLE
Give real error messages in exceptions

### ISSUE THREAD

**Issue by elwinar** [neomerx/json-api#93]
Debugging errors when using this lib is actually painful, because the exception messages doesn't give any information at all, forcing the user to dig into the code to find what the error is.
Worst, the Exception factory makes the first level of the stack trace useless as well.

I'm forking to add better exceptions, any guidelines/wish about that ?
Do you think it deserve a dedicated branch ? (I don't, it doesn't change anything to features).

**Comment by neomerx** [comment]
It's always nice to hear _"I'll prove I can to it beta than you"_

Please post to `feature/issue93`branch

**Comment by neomerx** [comment]
Localization would be really nice. I'd like to have it however haven't figured out how to do it elegantly without 3rd party libs.

**Comment by neomerx** [comment]
Factory is fine. My suggestion is to replace

``` php
(...) ?: Exceptions::throwInvalidArgument('meta', $meta);
```

with

``` php
if (...) {
   throw Exceptions::createInvalidArgument('meta', $meta);
}
```

but it will require adding about 50 new tests just get coverage back to 100%

**Comment by elwinar** [comment]
First, sorry if I sounded rude, it was not my intention. I meant to say something along the lines "I know it is difficult for the author of a lib to have insight about the actual usability of the lib, so I will lend you a hand on that.".

The factory itself is fine, it just shouldn't throw the exception itself. It indeed provide a fine way to implement things like l12n. Your suggestion is good, I don't mind spending an entire night fixing the tests.

My point is that if you fail to provide the mapping type => schema for a class, here is the exception you get: `type`. And the first item of the stack trace is something like that:

```
{
  "args": [
    "type",
    "Synthesio\\Component\\Site\\Model\\Community"
  ],
  "class": "Neomerx\\JsonApi\\Factories\\Exceptions",
  "file": "/data/api-capelo/vendor/neomerx/json-api/src/Schema/Container.php",
  "function": "throwInvalidArgument",
  "line": 121,
  "type": "::"
}
```

The first time I encountered it, I lost 2 hours on it and had to dig in the code to find what was the problem (a misspelled class name). The message should at least tell exactly what the problem is without having to read the source…

**Comment by eduardmartinez** [comment]
+1

**Comment by neomerx** [comment]
This PR is easy in terms of required library knowledge. The problem with it it has many places for trivial changes and most boringly writing tests for exceptions. It's difficult for 1 person but a few people can do it.

**Comment by elwinar** [comment]
I've done a [first draft](https://github.com/elwinar/json-api/commit/ed583092ad3ddc3f00f6cdc9cb464afa7a9010bc), would you be so kind as to review it ?
As I don't know much about the library internals, I've used the conditions to write the error message, or the comment when there was one. That not always ideal, but I think its a good start. I'm currently doing some work this the fork to try to get a feeling of the new exceptions.

> it will require adding about 50 new tests just get coverage back to 100%

The tests are fine, although the coverage downed a little. Note that the tests themselves didn't changed, nor the logic. 100% lines covered != 100% coverage….
Do you want me to add new unit tests ?

**Comment by neomerx** [comment]
Guys after thinking a while we can significantly simplify this issue. Yes it has nearly 50 places where exception are thrown like `Exceptions::throw...` but in reality people bump into a very few
- Schema is not registered for resource type $resourceType **number 1** (with 95% 
  probability you're annoyed with exactly this and only one `Schema/Container.php#142 and #120`)
- Resource type should not be used more than once to register a schema (`Schema/Container.php#78 that's another 4%)
- Check resource type and sub-URL are set for the Schema (`Schema/SchemaProvider.php#81 and 85` 0,99%)

And a couple of more
- "type" and "id" are reserved keywords and cannot be used as resource object attributes (`Document/Presenters/ElementPresenter.php#295`)
- "self" is a reserved keyword and cannot be used as a related resource link name (`Document/Presenters/ElementPresenter.php#253`)

So I propose to change these 3-5 places.

**Comment by elwinar** [comment]
Well… I made descriptive exception messages for (almost) all of the cases you give.
- https://github.com/elwinar/json-api/blob/feature/issue93/src/Schema/Container.php#L127
- https://github.com/elwinar/json-api/blob/feature/issue93/src/Schema/Container.php#L155
- https://github.com/elwinar/json-api/blob/feature/issue93/src/Schema/Container.php#L82
- https://github.com/elwinar/json-api/blob/feature/issue93/src/Document/Presenters/ElementPresenter.php#L258
- https://github.com/elwinar/json-api/blob/feature/issue93/src/Document/Presenters/ElementPresenter.php#L301
- https://github.com/elwinar/json-api/blob/feature/issue93/src/Document/Presenters/ElementPresenter.php#L305

For the unit-tests… If you change from

```
(...) ?: Exceptions::throwInvalidArgument('meta', $meta);
```

to 

```
if (...) {
   throw Exceptions::createInvalidArgument('meta', $meta);
}
```

and you coverage get down, then you weren't covering the case in the first place. The _percentage of line covered_ metric isn't equal to the _percentage of cases covered_ one, and the only one that counts is the second one.

Sadly, the PHPUnit coverage tool only use the first one, which is tricked by style conventions…

My advice in this case is either to keep the new coverage (96.83% isn't a value to be ashamed of) or add unit tests. Reverting back to the old style is a scam.

**Comment by neomerx** [comment]
another option is moving to PHP7 where type check is embedded which makes redundant 80%-90% of those checks.

**Comment by elwinar** [comment]
Rightly said. But PHP7 isn't currently an official release, so moving to it now would be a bit premature in my opinion.

**Comment by lindyhopchris** [comment]
yeah, php 7 isn't going to be an option until the 5 series is end of life, as there's going to be lots of applications out there using 5.6 for quite some time.

The test coverage on this package is really great - I wouldn't worry about it dropping below 100% if the only thing that isn't covered is invalid argument exceptions being thrown. IMHO better debugging (Exception) messages is more important than the coverage dropping to 96%

**Comment by neomerx** [comment]
Added detailed exception messages for places from the list above (and a few more).

Personal discover: an exception in PHP holds a stack frame where is was created but not thrown.

**Comment by elwinar** [comment]
I suppose you don't need my fork anymore ?
Do you have an idea when you will release the new version on composer ?

**Comment by neomerx** [comment]
Will be merged to master this week. If I have time during the week or weekend.

I'm locking the issue to keep it open until the merge.
