### ISSUE TITLE
Is it possible for a `SchemaProvider` to be given constructor parameters?

### ISSUE THREAD

**Issue by simensen** [neomerx/json-api#94]
It isn't immediately obvious if it is possible for a `SchemaProvider` to be constructed and passed rather than assuming there is a no argument constructor.

Alternately, I'm wondering how I might use the container to access my own services. I already have a container so not sure what the best way would be to get services into/out of the container.

I'd much rather have the ability to do constructor injection in my schema's than having to go container diving, but if there is no way to do constructor injection (and no way to do it easily even if I wanted to implement it and send a PR back to you) I'd settle for container diving. :)

**Comment by neomerx** [comment]
Constructor must accept (and sent to parent) `$factory` and `$container`. Sample [here](https://github.com/neomerx/json-api/wiki#encoder-instance).

Container returns a `Schema` for given resource. The full methods list could be found [here](https://github.com/neomerx/json-api/blob/master/src/Contracts/Schema/ContainerInterface.php).

I haven't understood your idea about injection for schema constructor. Can you give an example how usage will look like?

**Comment by nickelozz** [comment]
Hi guys!

I'm not sure if it's the same scenario as @simensen but I've been facing some issues with the schema's way of loading relationships... I'll try to ellaborate:

I have a resource that allows relationships to be added in both creation and update, these relationships are optional so no "default includes"... however regardless of how I do it...it seems like after the creation with relationships assign... the `getRelationships()` method of my schema doesn't recieve any relationship... I'm not sure if especifically the `array $includeRelationships = []` parameter only recieves values given to the `?include=relationshipName` query parameter but I havent figured out a way to pass the relationships I need so once the resource is created...it can be returned with the given relationships.

Perhaps I'm not seeing something here... I'd appreciate any help you can give me... thanks.

Note: I'm using Laravel 5 and I have already eager loaded all the needed relationships and verified they are accessible after creation/update on the object.

**Comment by simensen** [comment]
@neomerx the use case is if I need to get additional information about a model than was provided just by data. Say the data includes a user ID and I want to enrich the API response (via the schema) to get the username and other metadata about the user in getAttributes. In that case it would be nice to be able to inject a service or repository into the schema so that it can get the information it needs.

Important to note, I've been trying to find a few ways to represent metadata around my read models. I was trying to figure out the best place to do this at another layer (a layer I had written off as too complex/inappropriate for Reasons) so this is not a critical thing for me.

_However_, I suspect it may come up again where I might want to inject dependencies somehow so I can leverage other translation logic from somewhere to aid in constructing my schema. So I'm happy to continue working through this if you deem it worthy.

---

I'm not sure if this use case lines up well with @nickelozz so I won't speak on that. :) if that issue is more pressing and related to my original post enough, feel free to continue to work through it here!

**Comment by neomerx** [comment]
@nickelozz I've read it twice (yesterday and today) and haven't understood it :smile:  Anyway this question relates to other project (Collins or Shot).

**Comment by neomerx** [comment]
@simensen This project is framework agnostic. Things like DI and resource relations (ORM) are typically parts of a framework. I think if this lib starts partly replicate such framework pieces it will worsen the lib.

For example in Laravel your idea might look like (as far as I understand it)

``` php
...
    public function getAttributes($post)
    {
        $someDiService = app(SomeServiceInterface::class);
        $authorId      = post->author_id;

        return [
            'title'                   => $post->title,
            'author_car_plate_number' => $post->author->car->plate->number,
            'extra_info'              => $someDiService->getSomeUserInfo($authorId),
        ];
    }
...
```

**Comment by simensen** [comment]
@neomerx I'm not asking to replicate framework pieces and the reason I'm using this project is because I like the fact that it is framework agnostic. :)

Your laravel example is reasonable but I prefer to have a way to inject such dependencies by some mechanism instead of having to rely on some global resource locator.

If this comes up for me again as an actual issue I will try to fix it and send a PR so we can discuss it again. Thanks for your time and looking forward to working with you and this project more in the future!

**Comment by neomerx** [comment]
@simensen Sure, if you see it could be improved in some way I'd like to discuss that.
