### ISSUE TITLE
Sample app has a bug in EncodingParameters

### ISSUE THREAD

**Issue by hglattergotz** [neomerx/json-api#96]
In the `showSparseAndFieldSetsExample()` method of the [sample application on line 88](https://github.com/neomerx/json-api/blob/master/sample/sample.php#L88) the `$includePaths` parameter is declared as `['posts.authors']` but only the site resources is shown.
Changing the parameter to `[]` displays the full document as expected, but changing this to any value simply includes the site resource.
One would expect `['posts']` to include the posts resource as a related resource, but it does not.

**Comment by neomerx** [comment]
Actually I have [very similar test](https://github.com/neomerx/json-api/blob/master/tests/Encoder/EncodeIncludedObjectsTest.php#L159) which appears to be OK. I'll look closer what's the problem with sample app.

**Comment by neomerx** [comment]
That's a bug in the sample app. As fieldset is actually attributes **and** relationships the proper `EncodingParameters` should be (for example)

``` php
        $options = new EncodingParameters([
            // Paths to be included. Note 'posts.comments' will not be shown.
            'posts.author'
        ], [
            // Attributes and relationships that should be shown
            'sites'  => ['name', 'posts'],
            'posts'  => ['author'],
            'people' => ['first_name'],
        ]);
```

which will give

``` json
{
    "data":{
        "type":"sites",
        "id":"1",
        "attributes":{
            "name":"JSON API Samples"
        },
        "relationships":{
            "posts":{
                "data":[
                    {
                        "type":"posts",
                        "id":"321"
                    }
                ]
            }
        },
        "links":{
            "self":"/sites/1"
        }
    },
    "included":[
        {
            "type":"people",
            "id":"123",
            "attributes":{
                "first_name":"John"
            }
        },
        {
            "type":"posts",
            "id":"321",
            "relationships":{
                "author":{
                    "data":{
                        "type":"people",
                        "id":"123"
                    }
                }
            }
        }
    ]
}
```

I'll update the sample and close the issue.

**Comment by hglattergotz** [comment]
Thanks for the clarification. I played around with that a bit and it seems to work.
However, just a comment on this behavior: As someone new to the library, this way of specifying/configuring the include parameter does not feel intuitive.

I would expect to be able to specify the include paths and field sets separately. Mixing in the links with the fields array seems messy. Not sure how else to do it though?
Maybe a nested array?

``` php
$options  = new EncodingParameters(
    ['posts.author'],
    [
        'sites'  => [
            'fields' => ['name'],
            'links' => ['posts']
        ],
        'posts' => ['links' => ['author']],
        'people' => ['fields' => ['first_name']]
    ]
);
```

Then again, this would make even more sense (to me at least):

``` php
$options  = new EncodingParameters(
    ['posts.author'],
    [
        'sites'  => ['name'],
        'people' => ['first_name']
    ]
);
```

**Comment by neomerx** [comment]
- Breaking change
- It won't be able to distinguish attributes from relationships as a result it's just a matter of time for a bug to be posted

**Comment by hglattergotz** [comment]
Not sure I follow that. But I am sure there is a technical reason for it.
Thanks for looking into it.

**Comment by neomerx** [comment]
Will be closed when merged to master. Issue locked.
